Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq Class Reference
org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq Class Reference
Inherits Activity.
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
void onResume ()
void onPause ()
void onBackPressed ()
void onDestroy ()
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Attributes
final String TAG = UiAboutMobuzzFaq.class.getName()
Typeface font
Detailed Description
Definition at line 18 of file UiAboutMobuzzFaq.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.onBackPressed ()
Definition at line 114 of file UiAboutMobuzzFaq.java.
References org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.TAG.
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.onCreate (Bundle savedInstanceState) protected
Definition at line 41 of file UiAboutMobuzzFaq.java.
References org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.font, org.cosmic.mobuzz.general.util.LogAction.START, and org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.TAG.
boolean org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.onCreateOptionsMenu (Menu menu)
Definition at line 97 of file UiAboutMobuzzFaq.java.
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.onDestroy ()
Definition at line 121 of file UiAboutMobuzzFaq.java.
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.onPause ()
Definition at line 108 of file UiAboutMobuzzFaq.java.
References org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.TAG.
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.onResume ()
Definition at line 102 of file UiAboutMobuzzFaq.java.
References org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.TAG.
Member Data Documentation
Typeface org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.font private
Definition at line 23 of file UiAboutMobuzzFaq.java.
Referenced by org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.onCreate().
final String org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.TAG = UiAboutMobuzzFaq.class.getName() private
Definition at line 22 of file UiAboutMobuzzFaq.java.
Referenced by org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.onBackPressed(), org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.onCreate(), org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.onPause(), and org.cosmic.mobuzz.general.ui.UiAboutMobuzzFaq.onResume().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiAboutMobuzzFaq.java