Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiProfileRegister Class Reference
org.cosmic.mobuzz.general.ui.UiProfileRegister Class Reference
Inherits Activity.
Classes
class RegisterTask
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
boolean onOptionsItemSelected (MenuItem item)
void onBackPressed ()
void onDestroy ()
void onResume ()
void onPause ()
Protected Member Functions
void onCreate (Bundle savedInstanceState)
boolean validate ()
Private Member Functions
void edt_username_TextChanged ()
void but_residence_Click ()
void but_language_Click ()
void but_submit_Click ()
void regTask ()
boolean usernameValidate (String value, EditText view)
boolean passwordValidate (String value, String username, EditText view)
boolean passwordsValidate (String password1, String password2, EditText view)
boolean contactValidate (String value, EditText view)
boolean wardtValidate (String value, EditText view)
boolean spinnerValidate (String value, Button but)
boolean emailValidate (String value, EditText view)
boolean nameValidate (String value, EditText view)
void but_gender_Click ()
void showDialogResidence ()
void showDialogGender ()
void showDialogLanguage ()
boolean isNetworkAvailable ()
void popdNoInternet ()
void popdRegister (String title, String content, boolean resetdata)
void popdListLanguage ()
void popdListResidence ()
void popdListGender ()
void popdRequestFailed (String title, String content)
Private Attributes
final Context context = UiProfileRegister.this
EditText edt_email
Button but_submit
Typeface font
Dialog progressDialog
Pattern pattern
Matcher matcher
String[] residenceArray
String name
String TAG = UiProfileRegister.class.getName()
String url_profile_register
Static Private Attributes
static final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$"
Detailed Description
Definition at line 46 of file UiProfileRegister.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiProfileRegister.but_gender_Click () private
Definition at line 497 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.showDialogGender().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreate().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.but_language_Click () private
Definition at line 233 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.showDialogLanguage().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreate().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.but_residence_Click () private
Definition at line 221 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.showDialogResidence().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreate().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.but_submit_Click () private
Definition at line 245 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.isNetworkAvailable(), org.cosmic.mobuzz.general.ui.UiProfileRegister.popdNoInternet(), org.cosmic.mobuzz.general.ui.UiProfileRegister.regTask(), and org.cosmic.mobuzz.general.ui.UiProfileRegister.validate().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreate().
boolean org.cosmic.mobuzz.general.ui.UiProfileRegister.contactValidate (String value, EditText view) private
Definition at line 367 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.validate().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.edt_username_TextChanged () private
Definition at line 175 of file UiProfileRegister.java.
boolean org.cosmic.mobuzz.general.ui.UiProfileRegister.emailValidate (String value, EditText view) private
Definition at line 449 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.EMAIL_PATTERN, org.cosmic.mobuzz.general.ui.UiProfileRegister.matcher, and org.cosmic.mobuzz.general.ui.UiProfileRegister.pattern.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.validate().
boolean org.cosmic.mobuzz.general.ui.UiProfileRegister.isNetworkAvailable () private
Definition at line 599 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.context.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.but_submit_Click().
boolean org.cosmic.mobuzz.general.ui.UiProfileRegister.nameValidate (String value, EditText view) private
Definition at line 467 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.validate().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.onBackPressed ()
Definition at line 162 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.context, and org.cosmic.mobuzz.general.ui.UiProfileRegister.TAG.
void org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreate (Bundle savedInstanceState) protected
Definition at line 68 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.but_gender_Click(), org.cosmic.mobuzz.general.ui.UiProfileRegister.but_language_Click(), org.cosmic.mobuzz.general.ui.UiProfileRegister.but_residence_Click(), org.cosmic.mobuzz.general.ui.UiProfileRegister.but_submit, org.cosmic.mobuzz.general.ui.UiProfileRegister.but_submit_Click(), org.cosmic.mobuzz.general.ui.UiProfileRegister.context, org.cosmic.mobuzz.general.ui.UiProfileRegister.edt_email, org.cosmic.mobuzz.general.ui.UiProfileRegister.font, org.cosmic.mobuzz.general.ui.UiProfileRegister.residenceArray, org.cosmic.mobuzz.general.util.LogAction.START, org.cosmic.mobuzz.general.ui.UiProfileRegister.TAG, and org.cosmic.mobuzz.general.ui.UiProfileRegister.url_profile_register.
boolean org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreateOptionsMenu (Menu menu)
Definition at line 123 of file UiProfileRegister.java.
void org.cosmic.mobuzz.general.ui.UiProfileRegister.onDestroy ()
Definition at line 169 of file UiProfileRegister.java.
boolean org.cosmic.mobuzz.general.ui.UiProfileRegister.onOptionsItemSelected (MenuItem item)
Definition at line 130 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.context.
void org.cosmic.mobuzz.general.ui.UiProfileRegister.onPause ()
Definition at line 488 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.context, and org.cosmic.mobuzz.general.ui.UiProfileRegister.TAG.
void org.cosmic.mobuzz.general.ui.UiProfileRegister.onResume ()
Definition at line 482 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.context, and org.cosmic.mobuzz.general.ui.UiProfileRegister.TAG.
boolean org.cosmic.mobuzz.general.ui.UiProfileRegister.passwordsValidate (String password1, String password2, EditText view) private
Definition at line 357 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.validate().
boolean org.cosmic.mobuzz.general.ui.UiProfileRegister.passwordValidate (String value, String username, EditText view) private
Definition at line 338 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.validate().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListGender () private
Definition at line 736 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.context, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.showDialogGender().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListLanguage () private
Definition at line 636 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.context, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.showDialogLanguage().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListResidence () private
Definition at line 686 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.context, org.cosmic.mobuzz.general.ui.UiProfileRegister.residenceArray, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.showDialogResidence().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.popdNoInternet () private
Definition at line 610 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.but_submit_Click().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.popdRegister (String title, String content, boolean resetdata) private
Definition at line 617 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.context.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.responseToResult().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.popdRequestFailed (String title, String content) private
Definition at line 786 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.responseToResult().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.regTask () private
Definition at line 264 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.context, org.cosmic.mobuzz.general.ui.UiProfileRegister.name, and org.cosmic.mobuzz.general.ui.UiProfileRegister.url_profile_register.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.but_submit_Click().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.showDialogGender () private
Definition at line 522 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListGender().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.but_gender_Click().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.showDialogLanguage () private
Definition at line 530 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListLanguage().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.but_language_Click().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.showDialogResidence () private
Definition at line 514 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListResidence().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.but_residence_Click().
boolean org.cosmic.mobuzz.general.ui.UiProfileRegister.spinnerValidate (String value, Button but) private
Definition at line 434 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.validate().
boolean org.cosmic.mobuzz.general.ui.UiProfileRegister.usernameValidate (String value, EditText view) private
Definition at line 319 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.validate().
boolean org.cosmic.mobuzz.general.ui.UiProfileRegister.validate () protected
Definition at line 276 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.contactValidate(), org.cosmic.mobuzz.general.ui.UiProfileRegister.edt_email, org.cosmic.mobuzz.general.ui.UiProfileRegister.emailValidate(), org.cosmic.mobuzz.general.ui.UiProfileRegister.name, org.cosmic.mobuzz.general.ui.UiProfileRegister.nameValidate(), org.cosmic.mobuzz.general.ui.UiProfileRegister.passwordsValidate(), org.cosmic.mobuzz.general.ui.UiProfileRegister.passwordValidate(), org.cosmic.mobuzz.general.ui.UiProfileRegister.spinnerValidate(), org.cosmic.mobuzz.general.ui.UiProfileRegister.usernameValidate(), and org.cosmic.mobuzz.general.ui.UiProfileRegister.wardtValidate().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.but_submit_Click().
boolean org.cosmic.mobuzz.general.ui.UiProfileRegister.wardtValidate (String value, EditText view) private
Definition at line 377 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.validate().
Member Data Documentation
Button org.cosmic.mobuzz.general.ui.UiProfileRegister.but_submit private
Definition at line 51 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreate().
final Context org.cosmic.mobuzz.general.ui.UiProfileRegister.context = UiProfileRegister.this private
Definition at line 48 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.isNetworkAvailable(), org.cosmic.mobuzz.general.ui.UiProfileRegister.onBackPressed(), org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreate(), org.cosmic.mobuzz.general.ui.UiProfileRegister.onOptionsItemSelected(), org.cosmic.mobuzz.general.ui.UiProfileRegister.onPause(), org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.onPreExecute(), org.cosmic.mobuzz.general.ui.UiProfileRegister.onResume(), org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListGender(), org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListLanguage(), org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListResidence(), org.cosmic.mobuzz.general.ui.UiProfileRegister.popdRegister(), and org.cosmic.mobuzz.general.ui.UiProfileRegister.regTask().
EditText org.cosmic.mobuzz.general.ui.UiProfileRegister.edt_email private
Definition at line 50 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreate(), and org.cosmic.mobuzz.general.ui.UiProfileRegister.validate().
final String org.cosmic.mobuzz.general.ui.UiProfileRegister.EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$" static private
Definition at line 55 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.emailValidate().
Typeface org.cosmic.mobuzz.general.ui.UiProfileRegister.font private
Definition at line 52 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreate().
Matcher org.cosmic.mobuzz.general.ui.UiProfileRegister.matcher private
Definition at line 57 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.emailValidate().
String org.cosmic.mobuzz.general.ui.UiProfileRegister.name private
Definition at line 61 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.regTask(), and org.cosmic.mobuzz.general.ui.UiProfileRegister.validate().
Pattern org.cosmic.mobuzz.general.ui.UiProfileRegister.pattern private
Definition at line 56 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.emailValidate().
Dialog org.cosmic.mobuzz.general.ui.UiProfileRegister.progressDialog private
Definition at line 53 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.onPostExecute(), and org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.onPreExecute().
String [] org.cosmic.mobuzz.general.ui.UiProfileRegister.residenceArray private
Definition at line 59 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreate(), and org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListResidence().
String org.cosmic.mobuzz.general.ui.UiProfileRegister.TAG = UiProfileRegister.class.getName() private
Definition at line 62 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.onBackPressed(), org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreate(), org.cosmic.mobuzz.general.ui.UiProfileRegister.onPause(), org.cosmic.mobuzz.general.ui.UiProfileRegister.onResume(), and org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.responseToResult().
String org.cosmic.mobuzz.general.ui.UiProfileRegister.url_profile_register private
Definition at line 63 of file UiProfileRegister.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.onCreate(), and org.cosmic.mobuzz.general.ui.UiProfileRegister.regTask().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiProfileRegister.java