Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiMain Class Reference
org.cosmic.mobuzz.general.ui.UiMain Class Reference
Inherits Activity.
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
void onResume ()
void onPause ()
void onBackPressed ()
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
void rdg_main_navigation ()
void but_home ()
void but_profile ()
void but_info ()
void popdExit ()
Private Attributes
final String TAG = UiMain.class.getName()
Detailed Description
Definition at line 28 of file UiMain.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiMain.but_home () private
Definition at line 141 of file UiMain.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMain.rdg_main_navigation().
void org.cosmic.mobuzz.general.ui.UiMain.but_info () private
Definition at line 160 of file UiMain.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMain.rdg_main_navigation().
void org.cosmic.mobuzz.general.ui.UiMain.but_profile () private
Definition at line 151 of file UiMain.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMain.rdg_main_navigation().
void org.cosmic.mobuzz.general.ui.UiMain.onBackPressed ()
Definition at line 81 of file UiMain.java.
References org.cosmic.mobuzz.general.ui.UiMain.popdExit().
void org.cosmic.mobuzz.general.ui.UiMain.onCreate (Bundle savedInstanceState) protected
Definition at line 42 of file UiMain.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, org.cosmic.mobuzz.general.ui.UiMain.rdg_main_navigation(), org.cosmic.mobuzz.general.util.LogAction.START, and org.cosmic.mobuzz.general.ui.UiMain.TAG.
boolean org.cosmic.mobuzz.general.ui.UiMain.onCreateOptionsMenu (Menu menu)
Definition at line 64 of file UiMain.java.
void org.cosmic.mobuzz.general.ui.UiMain.onPause ()
Definition at line 75 of file UiMain.java.
References org.cosmic.mobuzz.general.ui.UiMain.TAG.
void org.cosmic.mobuzz.general.ui.UiMain.onResume ()
Definition at line 69 of file UiMain.java.
References org.cosmic.mobuzz.general.ui.UiMain.TAG.
void org.cosmic.mobuzz.general.ui.UiMain.popdExit () private
Definition at line 171 of file UiMain.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMain.onBackPressed().
void org.cosmic.mobuzz.general.ui.UiMain.rdg_main_navigation () private
Definition at line 85 of file UiMain.java.
References org.cosmic.mobuzz.general.ui.UiMain.but_home(), org.cosmic.mobuzz.general.ui.UiMain.but_info(), and org.cosmic.mobuzz.general.ui.UiMain.but_profile().
Referenced by org.cosmic.mobuzz.general.ui.UiMain.onCreate().
Member Data Documentation
final String org.cosmic.mobuzz.general.ui.UiMain.TAG = UiMain.class.getName() private
Definition at line 39 of file UiMain.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMain.onCreate(), org.cosmic.mobuzz.general.ui.UiMain.onPause(), and org.cosmic.mobuzz.general.ui.UiMain.onResume().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiMain.java