Mo-BuzzPHI: org.cosmic.mobuzz.general.util.GlobalMethods Class Reference
org.cosmic.mobuzz.general.util.GlobalMethods Class Reference
Static Public Member Functions
static Typeface getTypeface (Context context)
static Typeface getTypeface (Context context, String lang)
static boolean validateString (String value)
static Point getDisplaySize (Activity activity)
static int getInSampleSize (int imgHeight, int imgWidth, int viewHeight, int viewWidth)
static Point getImageSize (Uri imgUri)
static String makeMD5 (String message)
static String hex (byte[] array)
static String getTimestamp ()
static void cleanMemory ()
static void applyFontRecursively (ViewGroup parent, Typeface font)
static String getUniqueId (TelephonyManager tm, Context context)
static String getDeviceName ()
static void changeLang (Activity activity, String lang)
Static Public Attributes
static Locale locale
Detailed Description
Definition at line 25 of file GlobalMethods.java.
Member Function Documentation
static void org.cosmic.mobuzz.general.util.GlobalMethods.applyFontRecursively (ViewGroup parent, Typeface font) static
Definition at line 147 of file GlobalMethods.java.
static void org.cosmic.mobuzz.general.util.GlobalMethods.changeLang (Activity activity, String lang) static
Definition at line 193 of file GlobalMethods.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.locale.
static void org.cosmic.mobuzz.general.util.GlobalMethods.cleanMemory () static
Definition at line 143 of file GlobalMethods.java.
static String org.cosmic.mobuzz.general.util.GlobalMethods.getDeviceName () static
Definition at line 178 of file GlobalMethods.java.
static Point org.cosmic.mobuzz.general.util.GlobalMethods.getDisplaySize (Activity activity) static
Definition at line 57 of file GlobalMethods.java.
static Point org.cosmic.mobuzz.general.util.GlobalMethods.getImageSize (Uri imgUri) static
Parameters
imgUri
Returns
image height and width
    Returns image dimensions from a absolute path
Definition at line 105 of file GlobalMethods.java.
static int org.cosmic.mobuzz.general.util.GlobalMethods.getInSampleSize (int imgHeight, int imgWidth, int viewHeight, int viewWidth) static
Parameters
image -Height
imgage -Width
view -Height
view -Width
Returns
in-sample-size
    Calculate the in-sample-size for the image and view
Definition at line 77 of file GlobalMethods.java.
static String org.cosmic.mobuzz.general.util.GlobalMethods.getTimestamp () static
Definition at line 137 of file GlobalMethods.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.SIMPLE_DATE_FORMAT.
static Typeface org.cosmic.mobuzz.general.util.GlobalMethods.getTypeface (Context context) static
Definition at line 27 of file GlobalMethods.java.
static Typeface org.cosmic.mobuzz.general.util.GlobalMethods.getTypeface (Context context, String lang) static
Definition at line 32 of file GlobalMethods.java.
static String org.cosmic.mobuzz.general.util.GlobalMethods.getUniqueId (TelephonyManager tm, Context context) static
Definition at line 164 of file GlobalMethods.java.
static String org.cosmic.mobuzz.general.util.GlobalMethods.hex (byte[] array) static
Definition at line 129 of file GlobalMethods.java.
Referenced by org.cosmic.mobuzz.general.util.GlobalMethods.makeMD5().
static String org.cosmic.mobuzz.general.util.GlobalMethods.makeMD5 (String message) static
Definition at line 120 of file GlobalMethods.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.hex().
static boolean org.cosmic.mobuzz.general.util.GlobalMethods.validateString (String value) static
Definition at line 49 of file GlobalMethods.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.but_saveimage_Click(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.decodeResult(), org.cosmic.mobuzz.general.ui.UiProfileRecover.doOnResult(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.galleryLoadCameraPic(), org.cosmic.mobuzz.general.pojo.HistoryPojo.getAddress(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getAddress(), org.cosmic.mobuzz.general.pojo.HistoryPojo.getAssessment(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getAssessment(), org.cosmic.mobuzz.general.pojo.HistoryPojo.getCmcMessage(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getCmcmessage(), org.cosmic.mobuzz.general.pojo.HistoryPojo.getDate(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getDate(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.getDiskImage(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.getGalleryImage(), org.cosmic.mobuzz.general.ui.UiMapReports.getGalleryImage(), org.cosmic.mobuzz.general.pojo.HistoryPojo.getGps(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getGps(), org.cosmic.mobuzz.general.pojo.HistoryPojo.getId(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getId(), org.cosmic.mobuzz.general.ui.UiProfile.getLogData(), org.cosmic.mobuzz.general.ui.UiProfileEdit.getLogData(), org.cosmic.mobuzz.general.ui.UiMapHotspots.getMohInfo(), org.cosmic.mobuzz.general.pojo.HistoryPojo.getRemarks(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getRemarks(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getUsername(), org.cosmic.mobuzz.general.pojo.HistoryPojo.getWard(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getWard(), org.cosmic.mobuzz.general.ui.UiMapReports.manageHotspots(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onActivityCreated(), org.cosmic.mobuzz.general.MainActivity.onCreate(), org.cosmic.mobuzz.general.util.PopupDialogWidget.onCreate(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onCreate(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGoogleMap(), org.cosmic.mobuzz.general.ui.UiMapReports.popdListAssessment(), org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListGender(), org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListLanguage(), org.cosmic.mobuzz.general.ui.UiProfileEdit.popdListLanguage(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdListrAssessment(), org.cosmic.mobuzz.general.ui.UiProfileRegister.popdListResidence(), org.cosmic.mobuzz.general.ui.UiProfileEdit.popdListrResidence(), org.cosmic.mobuzz.general.ui.UiMapReports.popdListWards(), org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo(), org.cosmic.mobuzz.general.ui.UiMapReports.popupDatePicker(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.responseToResult(), org.cosmic.mobuzz.general.MainActivity.responseToResult(), org.cosmic.mobuzz.general.ui.UiProfileLogin.responseToResult(), org.cosmic.mobuzz.general.ui.UiMapHotspots.responseToResult(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.responseToResult(), org.cosmic.mobuzz.general.ui.UiMapReports.responseToResult(), org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.responseToResult(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.responseToResult(), org.cosmic.mobuzz.general.ui.UiMapReports.responseToUpload(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setGalleryImage(), org.cosmic.mobuzz.general.ui.UiMapReports.setGalleryImage(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setGalleryImageUri(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setImageResize(), org.cosmic.mobuzz.general.util.CMCRegions.stringToLatLng(), org.cosmic.mobuzz.general.ui.UiProfileEdit.updateProfile(), org.cosmic.mobuzz.general.ui.UiProfile.updateViews(), org.cosmic.mobuzz.general.ui.UiProfileEdit.updateViews(), org.cosmic.mobuzz.general.network.HttpUpload.uploadData(), org.cosmic.mobuzz.general.network.HttpUpload.uploadDataCache(), org.cosmic.mobuzz.general.network.HttpUpload.uploadRequestData(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.uploadTask(), org.cosmic.mobuzz.general.ui.UiProfileEdit.validate(), and org.cosmic.mobuzz.general.ui.UiProfileRegister.wardtValidate().
Member Data Documentation
Locale org.cosmic.mobuzz.general.util.GlobalMethods.locale static
Definition at line 192 of file GlobalMethods.java.
Referenced by org.cosmic.mobuzz.general.util.GlobalMethods.changeLang().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/util/GlobalMethods.java