Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation Class Reference
org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation Class Reference
Inherits Activity.
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
void onResume ()
void onPause ()
void onBackPressed ()
void onDestroy ()
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Attributes
Typeface font
final String TAG = UiAboutMobuzzInformation.class.getName()
Detailed Description
Definition at line 16 of file UiAboutMobuzzInformation.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.onBackPressed ()
Definition at line 62 of file UiAboutMobuzzInformation.java.
References org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.TAG.
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.onCreate (Bundle savedInstanceState) protected
Definition at line 26 of file UiAboutMobuzzInformation.java.
References org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.font, org.cosmic.mobuzz.general.util.LogAction.START, and org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.TAG.
boolean org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.onCreateOptionsMenu (Menu menu)
Definition at line 45 of file UiAboutMobuzzInformation.java.
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.onDestroy ()
Definition at line 69 of file UiAboutMobuzzInformation.java.
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.onPause ()
Definition at line 56 of file UiAboutMobuzzInformation.java.
References org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.TAG.
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.onResume ()
Definition at line 50 of file UiAboutMobuzzInformation.java.
References org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.TAG.
Member Data Documentation
Typeface org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.font private
Definition at line 19 of file UiAboutMobuzzInformation.java.
Referenced by org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.onCreate().
final String org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.TAG = UiAboutMobuzzInformation.class.getName() private
Definition at line 23 of file UiAboutMobuzzInformation.java.
Referenced by org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.onBackPressed(), org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.onCreate(), org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.onPause(), and org.cosmic.mobuzz.general.ui.UiAboutMobuzzInformation.onResume().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiAboutMobuzzInformation.java