Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms Class Reference
org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms Class Reference
Inherits Fragment.
Public Member Functions
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onResume ()
void onPause ()
void setUserVisibleHint (boolean isFragmentVisible)
Private Attributes
final String TAG = UiEducationSubpageSymptoms.class.getName()
Detailed Description
Definition at line 16 of file UiEducationSubpageSymptoms.java.
Member Function Documentation
View org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 30 of file UiEducationSubpageSymptoms.java.
void org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms.onPause ()
Definition at line 63 of file UiEducationSubpageSymptoms.java.
References org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms.TAG.
void org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms.onResume ()
Definition at line 57 of file UiEducationSubpageSymptoms.java.
References org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms.TAG.
void org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms.setUserVisibleHint (boolean isFragmentVisible)
Definition at line 69 of file UiEducationSubpageSymptoms.java.
References org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms.TAG.
Member Data Documentation
final String org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms.TAG = UiEducationSubpageSymptoms.class.getName() private
Definition at line 28 of file UiEducationSubpageSymptoms.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms.onPause(), org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms.onResume(), and org.cosmic.mobuzz.general.ui.UiEducationSubpageSymptoms.setUserVisibleHint().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiEducationSubpageSymptoms.java