Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiGoogleMap Class Reference
org.cosmic.mobuzz.general.ui.UiGoogleMap Class Reference
Inherits FragmentActivity.
Public Member Functions
void onBackPressed ()
void onDestroy ()
boolean onCreateOptionsMenu (Menu menu)
void onResume ()
void onPause ()
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
void setUpMap ()
void popdUnclearGPS (String content)
Private Attributes
GoogleMap mMap
final Context context = UiGoogleMap.this
final String TAG = UiGoogleMap.class.getName()
CMCRegions cmcRegions
LatLng latLng
boolean isFirst = false
Double latitude = 0.0
Double longitude = 0.0
Detailed Description
Definition at line 35 of file UiGoogleMap.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiGoogleMap.onBackPressed ()
Definition at line 78 of file UiGoogleMap.java.
References org.cosmic.mobuzz.general.ui.UiGoogleMap.context, org.cosmic.mobuzz.general.ui.UiGoogleMap.latitude, org.cosmic.mobuzz.general.ui.UiGoogleMap.longitude, and org.cosmic.mobuzz.general.ui.UiGoogleMap.TAG.
void org.cosmic.mobuzz.general.ui.UiGoogleMap.onCreate (Bundle savedInstanceState) protected
Definition at line 52 of file UiGoogleMap.java.
References org.cosmic.mobuzz.general.ui.UiGoogleMap.cmcRegions, org.cosmic.mobuzz.general.ui.UiGoogleMap.context, org.cosmic.mobuzz.general.util.GlobalVariables.GPS_COLOMBO, org.cosmic.mobuzz.general.ui.UiGoogleMap.latLng, org.cosmic.mobuzz.general.ui.UiGoogleMap.setUpMap(), org.cosmic.mobuzz.general.util.LogAction.START, and org.cosmic.mobuzz.general.ui.UiGoogleMap.TAG.
boolean org.cosmic.mobuzz.general.ui.UiGoogleMap.onCreateOptionsMenu (Menu menu)
Definition at line 164 of file UiGoogleMap.java.
void org.cosmic.mobuzz.general.ui.UiGoogleMap.onDestroy ()
Definition at line 113 of file UiGoogleMap.java.
void org.cosmic.mobuzz.general.ui.UiGoogleMap.onPause ()
Definition at line 175 of file UiGoogleMap.java.
References org.cosmic.mobuzz.general.ui.UiGoogleMap.context, org.cosmic.mobuzz.general.ui.UiGoogleMap.mMap, and org.cosmic.mobuzz.general.ui.UiGoogleMap.TAG.
void org.cosmic.mobuzz.general.ui.UiGoogleMap.onResume ()
Definition at line 169 of file UiGoogleMap.java.
References org.cosmic.mobuzz.general.ui.UiGoogleMap.context, and org.cosmic.mobuzz.general.ui.UiGoogleMap.TAG.
void org.cosmic.mobuzz.general.ui.UiGoogleMap.popdUnclearGPS (String content) private
Definition at line 193 of file UiGoogleMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiGoogleMap.setUpMap().
void org.cosmic.mobuzz.general.ui.UiGoogleMap.setUpMap () private
Definition at line 117 of file UiGoogleMap.java.
References org.cosmic.mobuzz.general.ui.UiGoogleMap.cmcRegions, org.cosmic.mobuzz.general.util.GlobalVariables.COLOR_REGION_OVERLAY, org.cosmic.mobuzz.general.ui.UiGoogleMap.context, org.cosmic.mobuzz.general.ui.UiGoogleMap.isFirst, org.cosmic.mobuzz.general.util.CMCRegions.isInCMC(), org.cosmic.mobuzz.general.ui.UiGoogleMap.latitude, org.cosmic.mobuzz.general.ui.UiGoogleMap.latLng, org.cosmic.mobuzz.general.ui.UiGoogleMap.longitude, org.cosmic.mobuzz.general.ui.UiGoogleMap.mMap, and org.cosmic.mobuzz.general.ui.UiGoogleMap.popdUnclearGPS().
Referenced by org.cosmic.mobuzz.general.ui.UiGoogleMap.onCreate().
Member Data Documentation
CMCRegions org.cosmic.mobuzz.general.ui.UiGoogleMap.cmcRegions private
Definition at line 40 of file UiGoogleMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiGoogleMap.onCreate(), and org.cosmic.mobuzz.general.ui.UiGoogleMap.setUpMap().
final Context org.cosmic.mobuzz.general.ui.UiGoogleMap.context = UiGoogleMap.this private
Definition at line 38 of file UiGoogleMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiGoogleMap.onBackPressed(), org.cosmic.mobuzz.general.ui.UiGoogleMap.onCreate(), org.cosmic.mobuzz.general.ui.UiGoogleMap.onPause(), org.cosmic.mobuzz.general.ui.UiGoogleMap.onResume(), and org.cosmic.mobuzz.general.ui.UiGoogleMap.setUpMap().
boolean org.cosmic.mobuzz.general.ui.UiGoogleMap.isFirst = false private
Definition at line 46 of file UiGoogleMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiGoogleMap.setUpMap().
Double org.cosmic.mobuzz.general.ui.UiGoogleMap.latitude = 0.0 private
Definition at line 47 of file UiGoogleMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiGoogleMap.onBackPressed(), and org.cosmic.mobuzz.general.ui.UiGoogleMap.setUpMap().
LatLng org.cosmic.mobuzz.general.ui.UiGoogleMap.latLng private
Definition at line 44 of file UiGoogleMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiGoogleMap.onCreate(), and org.cosmic.mobuzz.general.ui.UiGoogleMap.setUpMap().
Double org.cosmic.mobuzz.general.ui.UiGoogleMap.longitude = 0.0 private
Definition at line 48 of file UiGoogleMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiGoogleMap.onBackPressed(), and org.cosmic.mobuzz.general.ui.UiGoogleMap.setUpMap().
GoogleMap org.cosmic.mobuzz.general.ui.UiGoogleMap.mMap private
Definition at line 37 of file UiGoogleMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiGoogleMap.onPause(), and org.cosmic.mobuzz.general.ui.UiGoogleMap.setUpMap().
final String org.cosmic.mobuzz.general.ui.UiGoogleMap.TAG = UiGoogleMap.class.getName() private
Definition at line 39 of file UiGoogleMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiGoogleMap.onBackPressed(), org.cosmic.mobuzz.general.ui.UiGoogleMap.onCreate(), org.cosmic.mobuzz.general.ui.UiGoogleMap.onPause(), and org.cosmic.mobuzz.general.ui.UiGoogleMap.onResume().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiGoogleMap.java