Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiProfile Class Reference
org.cosmic.mobuzz.general.ui.UiProfile Class Reference
Inherits Fragment.
Classes
class downloadData
Public Member Functions
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onResume ()
void onPause ()
String getJsongString ()
void updateViews (String result)
Private Member Functions
void but_edit_Click ()
void but_logout_Click ()
String getLogData ()
void logout ()
boolean isNetworkAvailable ()
void popdNoInternet ()
void popdRequestFailed (String title, String content)
void popdRequestFailedLogout (String title, String content)
void popdReauth (String title, String content)
Private Attributes
View fv
Dialog progressDialog
final String TAG = UiProfile.class.getName()
Detailed Description
Definition at line 40 of file UiProfile.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiProfile.but_edit_Click () private
Definition at line 87 of file UiProfile.java.
References org.cosmic.mobuzz.general.ui.UiProfile.isNetworkAvailable(), and org.cosmic.mobuzz.general.ui.UiProfile.popdNoInternet().
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.onCreateView().
void org.cosmic.mobuzz.general.ui.UiProfile.but_logout_Click () private
Definition at line 106 of file UiProfile.java.
References org.cosmic.mobuzz.general.ui.UiProfile.logout().
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.onCreateView().
String org.cosmic.mobuzz.general.ui.UiProfile.getJsongString ()
Definition at line 129 of file UiProfile.java.
References org.cosmic.mobuzz.general.ui.UiProfile.getLogData(), org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, and org.cosmic.mobuzz.general.ui.UiProfile.TAG.
String org.cosmic.mobuzz.general.ui.UiProfile.getLogData () private
Definition at line 150 of file UiProfile.java.
References org.cosmic.mobuzz.general.util.GlobalIO.getConfig(), org.cosmic.mobuzz.general.ui.UiProfile.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.getJsongString().
boolean org.cosmic.mobuzz.general.ui.UiProfile.isNetworkAvailable () private
Definition at line 299 of file UiProfile.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.but_edit_Click().
void org.cosmic.mobuzz.general.ui.UiProfile.logout () private
Definition at line 286 of file UiProfile.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.but_logout_Click(), and org.cosmic.mobuzz.general.ui.UiProfile.updateViews().
View org.cosmic.mobuzz.general.ui.UiProfile.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 52 of file UiProfile.java.
References org.cosmic.mobuzz.general.ui.UiProfile.but_edit_Click(), org.cosmic.mobuzz.general.ui.UiProfile.but_logout_Click(), org.cosmic.mobuzz.general.ui.UiProfile.fv, org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, and org.cosmic.mobuzz.general.ui.UiProfile.TAG.
void org.cosmic.mobuzz.general.ui.UiProfile.onPause ()
Definition at line 78 of file UiProfile.java.
References org.cosmic.mobuzz.general.ui.UiProfile.TAG.
void org.cosmic.mobuzz.general.ui.UiProfile.onResume ()
Definition at line 72 of file UiProfile.java.
References org.cosmic.mobuzz.general.ui.UiProfile.TAG.
void org.cosmic.mobuzz.general.ui.UiProfile.popdNoInternet () private
Definition at line 310 of file UiProfile.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.but_edit_Click().
void org.cosmic.mobuzz.general.ui.UiProfile.popdReauth (String title, String content) private
Definition at line 340 of file UiProfile.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.updateViews().
void org.cosmic.mobuzz.general.ui.UiProfile.popdRequestFailed (String title, String content) private
Definition at line 317 of file UiProfile.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.updateViews().
void org.cosmic.mobuzz.general.ui.UiProfile.popdRequestFailedLogout (String title, String content) private
Definition at line 324 of file UiProfile.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.updateViews().
void org.cosmic.mobuzz.general.ui.UiProfile.updateViews (String result)
Definition at line 210 of file UiProfile.java.
References org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getStatus(), org.cosmic.mobuzz.general.ui.UiProfile.logout(), org.cosmic.mobuzz.general.ui.UiProfile.popdReauth(), org.cosmic.mobuzz.general.ui.UiProfile.popdRequestFailed(), org.cosmic.mobuzz.general.ui.UiProfile.popdRequestFailedLogout(), org.cosmic.mobuzz.general.ui.UiProfile.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.downloadData.onPostExecute().
Member Data Documentation
View org.cosmic.mobuzz.general.ui.UiProfile.fv private
Definition at line 42 of file UiProfile.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.onCreateView().
Dialog org.cosmic.mobuzz.general.ui.UiProfile.progressDialog private
Definition at line 43 of file UiProfile.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.downloadData.onPostExecute(), and org.cosmic.mobuzz.general.ui.UiProfile.downloadData.onPreExecute().
final String org.cosmic.mobuzz.general.ui.UiProfile.TAG = UiProfile.class.getName() private
Definition at line 45 of file UiProfile.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.getJsongString(), org.cosmic.mobuzz.general.ui.UiProfile.getLogData(), org.cosmic.mobuzz.general.ui.UiProfile.onCreateView(), org.cosmic.mobuzz.general.ui.UiProfile.onPause(), org.cosmic.mobuzz.general.ui.UiProfile.onResume(), and org.cosmic.mobuzz.general.ui.UiProfile.updateViews().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiProfile.java