Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiProfileEdit Class Reference
org.cosmic.mobuzz.general.ui.UiProfileEdit Class Reference
Inherits Activity.
Classes
class downloadData
Public Member Functions
void onCreate (Bundle savedInstanceState)
void onResume ()
void onPause ()
void onBackPressed ()
void onDestroy ()
String getJsongString ()
void updateViews (String result)
Protected Member Functions
void getNewValues ()
Private Member Functions
void but_language_Click ()
void but_residence_Click ()
void but_logout_Click ()
void but_chpasswd_Click ()
String getLogData ()
void getProfieData ()
void but_edit_Click ()
void but_submit_Click ()
void updateProfile ()
boolean validate ()
void enableDisableView (View view, boolean enabled)
void logout ()
void showDialogResidence ()
void showDialogLanguage ()
boolean passwordValidate (String value, EditText view)
boolean passwordValidate (String password1, String password2, EditText view)
boolean contactValidate (String value, EditText view)
boolean spinnerValidate (String value, Button but)
boolean emailValidate (String value, EditText view)
boolean nameValidate (String value, EditText view)
boolean isNetworkAvailable ()
void popdNoInternet ()
void popdListLanguage ()
void popdListrResidence ()
void popdRequestFailed (String title, String content)
void popdLogin (String title, String content, boolean resetdata)
void popdReauth (String title, String content)
Private Attributes
final Context context = UiProfileEdit.this
EditText edt_email
Button but_edit
Dialog progressDialog
TextView txt_username
Typeface font
View fv
boolean signout
String[] languageArray
final String TAG = UiProfileEdit.class.getName()
Pattern pattern
Matcher matcher
String url_profile_edit
String url_profile_update
Static Private Attributes
static final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$"
Detailed Description
Definition at line 51 of file UiProfileEdit.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiProfileEdit.but_chpasswd_Click () private
Definition at line 226 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.but_edit_Click () private
Definition at line 302 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.enableDisableView(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.fv.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.but_language_Click () private
Definition at line 164 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.showDialogLanguage().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.but_logout_Click () private
Definition at line 203 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.logout().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.but_residence_Click () private
Definition at line 190 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.showDialogResidence().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.but_submit_Click () private
Definition at line 321 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.getNewValues().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate().
boolean org.cosmic.mobuzz.general.ui.UiProfileEdit.contactValidate (String value, EditText view) private
Definition at line 610 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.validate().
boolean org.cosmic.mobuzz.general.ui.UiProfileEdit.emailValidate (String value, EditText view) private
Definition at line 633 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.EMAIL_PATTERN, org.cosmic.mobuzz.general.ui.UiProfileEdit.matcher, and org.cosmic.mobuzz.general.ui.UiProfileEdit.pattern.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.validate().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.enableDisableView (View view, boolean enabled) private
Definition at line 418 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.but_edit_Click(), org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.updateViews().
String org.cosmic.mobuzz.general.ui.UiProfileEdit.getJsongString ()
Definition at line 241 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.getLogData(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.TAG.
String org.cosmic.mobuzz.general.ui.UiProfileEdit.getLogData () private
Definition at line 259 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.context, org.cosmic.mobuzz.general.util.GlobalIO.getConfig(), org.cosmic.mobuzz.general.ui.UiProfileEdit.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.getJsongString().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.getNewValues () protected
Definition at line 336 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.TAG, org.cosmic.mobuzz.general.ui.UiProfileEdit.updateProfile(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.validate().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.but_submit_Click().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.getProfieData () private
Definition at line 280 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.isNetworkAvailable(), org.cosmic.mobuzz.general.ui.UiProfileEdit.popdNoInternet(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.url_profile_edit.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate().
boolean org.cosmic.mobuzz.general.ui.UiProfileEdit.isNetworkAvailable () private
Definition at line 667 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.context.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.getProfieData(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.updateProfile().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.logout () private
Definition at line 554 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.context.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.but_logout_Click(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.updateViews().
boolean org.cosmic.mobuzz.general.ui.UiProfileEdit.nameValidate (String value, EditText view) private
Definition at line 650 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.validate().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.onBackPressed ()
Definition at line 178 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.context, and org.cosmic.mobuzz.general.ui.UiProfileEdit.TAG.
void org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate (Bundle savedInstanceState)
Definition at line 79 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.but_chpasswd_Click(), org.cosmic.mobuzz.general.ui.UiProfileEdit.but_edit, org.cosmic.mobuzz.general.ui.UiProfileEdit.but_edit_Click(), org.cosmic.mobuzz.general.ui.UiProfileEdit.but_language_Click(), org.cosmic.mobuzz.general.ui.UiProfileEdit.but_logout_Click(), org.cosmic.mobuzz.general.ui.UiProfileEdit.but_residence_Click(), org.cosmic.mobuzz.general.ui.UiProfileEdit.but_submit_Click(), org.cosmic.mobuzz.general.ui.UiProfileEdit.context, org.cosmic.mobuzz.general.ui.UiProfileEdit.edt_email, org.cosmic.mobuzz.general.ui.UiProfileEdit.enableDisableView(), org.cosmic.mobuzz.general.ui.UiProfileEdit.font, org.cosmic.mobuzz.general.ui.UiProfileEdit.fv, org.cosmic.mobuzz.general.ui.UiProfileEdit.getProfieData(), org.cosmic.mobuzz.general.ui.UiProfileEdit.languageArray, org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, org.cosmic.mobuzz.general.util.LogAction.START, org.cosmic.mobuzz.general.ui.UiProfileEdit.TAG, org.cosmic.mobuzz.general.ui.UiProfileEdit.txt_username, org.cosmic.mobuzz.general.ui.UiProfileEdit.url_profile_edit, and org.cosmic.mobuzz.general.ui.UiProfileEdit.url_profile_update.
void org.cosmic.mobuzz.general.ui.UiProfileEdit.onDestroy ()
Definition at line 185 of file UiProfileEdit.java.
void org.cosmic.mobuzz.general.ui.UiProfileEdit.onPause ()
Definition at line 155 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.context, and org.cosmic.mobuzz.general.ui.UiProfileEdit.TAG.
void org.cosmic.mobuzz.general.ui.UiProfileEdit.onResume ()
Definition at line 149 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.context, and org.cosmic.mobuzz.general.ui.UiProfileEdit.TAG.
boolean org.cosmic.mobuzz.general.ui.UiProfileEdit.passwordValidate (String value, EditText view) private
Definition at line 581 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.passwordValidate(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.validate().
boolean org.cosmic.mobuzz.general.ui.UiProfileEdit.passwordValidate (String password1, String password2, EditText view) private
Definition at line 595 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.passwordValidate().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.popdListLanguage () private
Definition at line 685 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.context, org.cosmic.mobuzz.general.ui.UiProfileEdit.languageArray, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.showDialogLanguage().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.popdListrResidence () private
Definition at line 735 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.context, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.showDialogResidence().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.popdLogin (String title, String content, boolean resetdata) private
Definition at line 840 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.context.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.updateViews().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.popdNoInternet () private
Definition at line 678 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.getProfieData(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.updateProfile().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.popdReauth (String title, String content) private
Definition at line 860 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.context, and org.cosmic.mobuzz.general.ui.UiProfileEdit.signout.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.updateViews().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.popdRequestFailed (String title, String content) private
Definition at line 833 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.updateViews().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.showDialogLanguage () private
Definition at line 576 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.popdListLanguage().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.but_language_Click().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.showDialogResidence () private
Definition at line 570 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.popdListrResidence().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.but_residence_Click().
boolean org.cosmic.mobuzz.general.ui.UiProfileEdit.spinnerValidate (String value, Button but) private
Definition at line 620 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.validate().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.updateProfile () private
Definition at line 370 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.isNetworkAvailable(), org.cosmic.mobuzz.general.ui.UiProfileEdit.popdNoInternet(), org.cosmic.mobuzz.general.ui.UiProfileEdit.url_profile_update, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.getNewValues().
void org.cosmic.mobuzz.general.ui.UiProfileEdit.updateViews (String result)
Definition at line 434 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.context, org.cosmic.mobuzz.general.ui.UiProfileEdit.enableDisableView(), org.cosmic.mobuzz.general.ui.UiProfileEdit.fv, org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getStatus(), org.cosmic.mobuzz.general.ui.UiProfileEdit.logout(), org.cosmic.mobuzz.general.ui.UiProfileEdit.popdLogin(), org.cosmic.mobuzz.general.ui.UiProfileEdit.popdReauth(), org.cosmic.mobuzz.general.ui.UiProfileEdit.popdRequestFailed(), org.cosmic.mobuzz.general.ui.UiProfileEdit.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.downloadData.onPostExecute().
boolean org.cosmic.mobuzz.general.ui.UiProfileEdit.validate () private
Definition at line 398 of file UiProfileEdit.java.
References org.cosmic.mobuzz.general.ui.UiProfileEdit.contactValidate(), org.cosmic.mobuzz.general.ui.UiProfileEdit.edt_email, org.cosmic.mobuzz.general.ui.UiProfileEdit.emailValidate(), org.cosmic.mobuzz.general.ui.UiProfileEdit.nameValidate(), org.cosmic.mobuzz.general.ui.UiProfileEdit.passwordValidate(), org.cosmic.mobuzz.general.ui.UiProfileEdit.spinnerValidate(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.getNewValues().
Member Data Documentation
Button org.cosmic.mobuzz.general.ui.UiProfileEdit.but_edit private
Definition at line 55 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate().
final Context org.cosmic.mobuzz.general.ui.UiProfileEdit.context = UiProfileEdit.this private
Definition at line 53 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.getLogData(), org.cosmic.mobuzz.general.ui.UiProfileEdit.isNetworkAvailable(), org.cosmic.mobuzz.general.ui.UiProfileEdit.logout(), org.cosmic.mobuzz.general.ui.UiProfileEdit.onBackPressed(), org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate(), org.cosmic.mobuzz.general.ui.UiProfileEdit.onPause(), org.cosmic.mobuzz.general.ui.UiProfileEdit.downloadData.onPreExecute(), org.cosmic.mobuzz.general.ui.UiProfileEdit.onResume(), org.cosmic.mobuzz.general.ui.UiProfileEdit.popdListLanguage(), org.cosmic.mobuzz.general.ui.UiProfileEdit.popdListrResidence(), org.cosmic.mobuzz.general.ui.UiProfileEdit.popdLogin(), org.cosmic.mobuzz.general.ui.UiProfileEdit.popdReauth(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.updateViews().
EditText org.cosmic.mobuzz.general.ui.UiProfileEdit.edt_email private
Definition at line 54 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.validate().
final String org.cosmic.mobuzz.general.ui.UiProfileEdit.EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$" static private
Definition at line 67 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.emailValidate().
Typeface org.cosmic.mobuzz.general.ui.UiProfileEdit.font private
Definition at line 58 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate().
View org.cosmic.mobuzz.general.ui.UiProfileEdit.fv private
Definition at line 59 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.but_edit_Click(), org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.updateViews().
String [] org.cosmic.mobuzz.general.ui.UiProfileEdit.languageArray private
Definition at line 61 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.popdListLanguage().
Matcher org.cosmic.mobuzz.general.ui.UiProfileEdit.matcher private
Definition at line 69 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.emailValidate().
Pattern org.cosmic.mobuzz.general.ui.UiProfileEdit.pattern private
Definition at line 68 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.emailValidate().
Dialog org.cosmic.mobuzz.general.ui.UiProfileEdit.progressDialog private
Definition at line 56 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.downloadData.onPostExecute(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.downloadData.onPreExecute().
boolean org.cosmic.mobuzz.general.ui.UiProfileEdit.signout private
Definition at line 60 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.downloadData.onPreExecute(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.popdReauth().
final String org.cosmic.mobuzz.general.ui.UiProfileEdit.TAG = UiProfileEdit.class.getName() private
Definition at line 66 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.getJsongString(), org.cosmic.mobuzz.general.ui.UiProfileEdit.getLogData(), org.cosmic.mobuzz.general.ui.UiProfileEdit.getNewValues(), org.cosmic.mobuzz.general.ui.UiProfileEdit.onBackPressed(), org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate(), org.cosmic.mobuzz.general.ui.UiProfileEdit.onPause(), org.cosmic.mobuzz.general.ui.UiProfileEdit.onResume(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.updateViews().
TextView org.cosmic.mobuzz.general.ui.UiProfileEdit.txt_username private
Definition at line 57 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate().
String org.cosmic.mobuzz.general.ui.UiProfileEdit.url_profile_edit private
Definition at line 71 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.getProfieData(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate().
String org.cosmic.mobuzz.general.ui.UiProfileEdit.url_profile_update private
Definition at line 72 of file UiProfileEdit.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileEdit.onCreate(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.updateProfile().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiProfileEdit.java