Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails Class Reference
org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails Class Reference
Inherits FragmentActivity.
Classes
class downloadImage
Public Member Functions
void onBackPressed ()
void onDestroy ()
boolean onCreateOptionsMenu (Menu menu)
void onResume ()
void onPause ()
void responseToResult (String result)
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
void but_actimage_Click ()
void getDiskImage (String imagepath)
void setGalleryImage (String imagePath)
String getGalleryImage (String imageName)
void but_saveimage_Click ()
void setImage (String imagesize)
void setData ()
void setUpMap ()
void popdRequestFailed (String title, String content)
void popdReauth (String title, String content)
void progress (String message)
Private Attributes
GoogleMap mMap
final Context context = UiBreedingsiteHistoryDetails.this
final String TAG = UiBreedingsiteHistoryDetails.class.getName()
String url_report_details
Dialog progressDialog
Detailed Description
Definition at line 58 of file UiBreedingsiteHistoryDetails.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.but_actimage_Click () private
Definition at line 174 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setImage().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onCreate().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.but_saveimage_Click () private
Definition at line 324 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.context, org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.getGalleryImage(), org.cosmic.mobuzz.general.pojo.ImagePojo.getImg_name(), org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onCreate().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.getDiskImage (String imagepath) private
Definition at line 185 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.getGalleryImage(), org.cosmic.mobuzz.general.util.GlobalVariables.IMAGE_THUMB_POSTFIX, org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setGalleryImage(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setImage(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onCreate().
String org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.getGalleryImage (String imageName) private
Definition at line 258 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.but_saveimage_Click(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.getDiskImage().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onBackPressed ()
Definition at line 161 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.context, and org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.TAG.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onCreate (Bundle savedInstanceState) protected
Definition at line 80 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.but_actimage_Click(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.but_saveimage_Click(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.context, org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.getDiskImage(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setData(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setUpMap(), org.cosmic.mobuzz.general.util.LogAction.START, org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.TAG, org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.url_report_details, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
boolean org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onCreateOptionsMenu (Menu menu)
Definition at line 440 of file UiBreedingsiteHistoryDetails.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onDestroy ()
Definition at line 169 of file UiBreedingsiteHistoryDetails.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onPause ()
Definition at line 451 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.context, and org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.TAG.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onResume ()
Definition at line 445 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.context, and org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.TAG.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.popdReauth (String title, String content) private
Definition at line 591 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.context.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.responseToResult().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.popdRequestFailed (String title, String content) private
Definition at line 584 of file UiBreedingsiteHistoryDetails.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.responseToResult().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.progress (String message) private
Definition at line 607 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.context, and org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.progressDialog.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.downloadImage.onPreExecute().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.responseToResult (String result)
Definition at line 489 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.pojo.ImagePojo.getImg_data(), org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getStatus(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.popdReauth(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.popdRequestFailed(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.downloadImage.onPostExecute().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setData () private
Definition at line 410 of file UiBreedingsiteHistoryDetails.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onCreate().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setGalleryImage (String imagePath) private
Definition at line 249 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.getDiskImage().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setImage (String imagesize) private
Definition at line 380 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.TAG, and org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.url_report_details.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.but_actimage_Click(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.getDiskImage().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setUpMap () private
Definition at line 421 of file UiBreedingsiteHistoryDetails.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.context, and org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.mMap.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onCreate().
Member Data Documentation
final Context org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.context = UiBreedingsiteHistoryDetails.this private
Definition at line 61 of file UiBreedingsiteHistoryDetails.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.but_saveimage_Click(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onBackPressed(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onCreate(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onPause(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onResume(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.popdReauth(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.progress(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setUpMap().
GoogleMap org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.mMap private
Definition at line 60 of file UiBreedingsiteHistoryDetails.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setUpMap().
Dialog org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.progressDialog private
Definition at line 64 of file UiBreedingsiteHistoryDetails.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.downloadImage.onPostExecute(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.progress().
final String org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.TAG = UiBreedingsiteHistoryDetails.class.getName() private
Definition at line 62 of file UiBreedingsiteHistoryDetails.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.but_saveimage_Click(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.getDiskImage(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.getGalleryImage(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onBackPressed(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onCreate(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onPause(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onResume(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.responseToResult(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setImage().
String org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.url_report_details private
Definition at line 63 of file UiBreedingsiteHistoryDetails.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.onCreate(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.setImage().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiBreedingsiteHistoryDetails.java