Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiMap Class Reference
org.cosmic.mobuzz.general.ui.UiMap Class Reference
Inherits Activity.
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
void onResume ()
void onPause ()
void onBackPressed ()
void onDestroy ()
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
void MapPages_Click ()
void rdg_main_navigation ()
void but_home ()
void but_profile ()
void but_info ()
Private Attributes
final String TAG = UiEducation.class.getName()
Detailed Description
Definition at line 19 of file UiMap.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiMap.but_home () private
Definition at line 123 of file UiMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMap.rdg_main_navigation().
void org.cosmic.mobuzz.general.ui.UiMap.but_info () private
Definition at line 140 of file UiMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMap.rdg_main_navigation().
void org.cosmic.mobuzz.general.ui.UiMap.but_profile () private
Definition at line 131 of file UiMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMap.rdg_main_navigation().
void org.cosmic.mobuzz.general.ui.UiMap.MapPages_Click () private
Definition at line 73 of file UiMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMap.onCreate().
void org.cosmic.mobuzz.general.ui.UiMap.onBackPressed ()
Definition at line 61 of file UiMap.java.
References org.cosmic.mobuzz.general.ui.UiMap.TAG.
void org.cosmic.mobuzz.general.ui.UiMap.onCreate (Bundle savedInstanceState) protected
Definition at line 30 of file UiMap.java.
References org.cosmic.mobuzz.general.ui.UiMap.MapPages_Click(), org.cosmic.mobuzz.general.ui.UiMap.rdg_main_navigation(), org.cosmic.mobuzz.general.util.LogAction.START, and org.cosmic.mobuzz.general.ui.UiMap.TAG.
boolean org.cosmic.mobuzz.general.ui.UiMap.onCreateOptionsMenu (Menu menu)
Definition at line 44 of file UiMap.java.
void org.cosmic.mobuzz.general.ui.UiMap.onDestroy ()
Definition at line 68 of file UiMap.java.
void org.cosmic.mobuzz.general.ui.UiMap.onPause ()
Definition at line 55 of file UiMap.java.
References org.cosmic.mobuzz.general.ui.UiMap.TAG.
void org.cosmic.mobuzz.general.ui.UiMap.onResume ()
Definition at line 49 of file UiMap.java.
References org.cosmic.mobuzz.general.ui.UiMap.TAG.
void org.cosmic.mobuzz.general.ui.UiMap.rdg_main_navigation () private
Definition at line 94 of file UiMap.java.
References org.cosmic.mobuzz.general.ui.UiMap.but_home(), org.cosmic.mobuzz.general.ui.UiMap.but_info(), and org.cosmic.mobuzz.general.ui.UiMap.but_profile().
Referenced by org.cosmic.mobuzz.general.ui.UiMap.onCreate().
Member Data Documentation
final String org.cosmic.mobuzz.general.ui.UiMap.TAG = UiEducation.class.getName() private
Definition at line 22 of file UiMap.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMap.onBackPressed(), org.cosmic.mobuzz.general.ui.UiMap.onCreate(), org.cosmic.mobuzz.general.ui.UiMap.onPause(), and org.cosmic.mobuzz.general.ui.UiMap.onResume().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiMap.java