Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiProfileLogin Class Reference
org.cosmic.mobuzz.general.ui.UiProfileLogin Class Reference
Inherits Activity.
Classes
class LoginTask
Public Member Functions
void onBackPressed ()
boolean onCreateOptionsMenu (Menu menu)
void onResume ()
void onPause ()
void onDestroy ()
void login ()
void responseToResult (String result)
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
void signinButton_Click ()
void forgotpwordTextView_Click ()
void registerTextView_Click ()
void attemptLogin ()
void loginTask ()
void makeLogin (String language)
boolean isNetworkAvailable ()
void popdNoInternet ()
void popdExit ()
void popdLogin (String title, String content, boolean resetdata)
void popdRequestFailed (String title, String content)
Private Attributes
final Context context = UiProfileLogin.this
String TAG = UiProfileLogin.class.getName()
EditText usernameET
Dialog progressDialog
Button signinButton
TextView registerTextView
String url_profile_login
Detailed Description
Definition at line 44 of file UiProfileLogin.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiProfileLogin.attemptLogin () private
Definition at line 186 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.isNetworkAvailable(), org.cosmic.mobuzz.general.ui.UiProfileLogin.loginTask(), and org.cosmic.mobuzz.general.ui.UiProfileLogin.popdNoInternet().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.login().
void org.cosmic.mobuzz.general.ui.UiProfileLogin.forgotpwordTextView_Click () private
Definition at line 130 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.context, org.cosmic.mobuzz.general.ui.UiProfileLogin.isNetworkAvailable(), and org.cosmic.mobuzz.general.ui.UiProfileLogin.popdNoInternet().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.onCreate().
boolean org.cosmic.mobuzz.general.ui.UiProfileLogin.isNetworkAvailable () private
Definition at line 361 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.context.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.attemptLogin(), org.cosmic.mobuzz.general.ui.UiProfileLogin.forgotpwordTextView_Click(), and org.cosmic.mobuzz.general.ui.UiProfileLogin.registerTextView_Click().
void org.cosmic.mobuzz.general.ui.UiProfileLogin.login ()
Definition at line 162 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.attemptLogin().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.signinButton_Click().
void org.cosmic.mobuzz.general.ui.UiProfileLogin.loginTask () private
Definition at line 196 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.context, and org.cosmic.mobuzz.general.ui.UiProfileLogin.url_profile_login.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.attemptLogin().
void org.cosmic.mobuzz.general.ui.UiProfileLogin.makeLogin (String language) private
Definition at line 343 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.context, and org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.responseToResult().
void org.cosmic.mobuzz.general.ui.UiProfileLogin.onBackPressed ()
Definition at line 89 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.popdExit().
void org.cosmic.mobuzz.general.ui.UiProfileLogin.onCreate (Bundle savedInstanceState) protected
Definition at line 59 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.context, org.cosmic.mobuzz.general.ui.UiProfileLogin.forgotpwordTextView_Click(), org.cosmic.mobuzz.general.ui.UiProfileLogin.registerTextView, org.cosmic.mobuzz.general.ui.UiProfileLogin.registerTextView_Click(), org.cosmic.mobuzz.general.ui.UiProfileLogin.signinButton, org.cosmic.mobuzz.general.ui.UiProfileLogin.signinButton_Click(), org.cosmic.mobuzz.general.util.LogAction.START, org.cosmic.mobuzz.general.ui.UiProfileLogin.TAG, org.cosmic.mobuzz.general.ui.UiProfileLogin.url_profile_login, and org.cosmic.mobuzz.general.ui.UiProfileLogin.usernameET.
boolean org.cosmic.mobuzz.general.ui.UiProfileLogin.onCreateOptionsMenu (Menu menu)
Definition at line 95 of file UiProfileLogin.java.
void org.cosmic.mobuzz.general.ui.UiProfileLogin.onDestroy ()
Definition at line 126 of file UiProfileLogin.java.
void org.cosmic.mobuzz.general.ui.UiProfileLogin.onPause ()
Definition at line 106 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.context, and org.cosmic.mobuzz.general.ui.UiProfileLogin.TAG.
void org.cosmic.mobuzz.general.ui.UiProfileLogin.onResume ()
Definition at line 100 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.context, and org.cosmic.mobuzz.general.ui.UiProfileLogin.TAG.
void org.cosmic.mobuzz.general.ui.UiProfileLogin.popdExit () private
Definition at line 379 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.context, and org.cosmic.mobuzz.general.ui.UiProfileLogin.TAG.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.onBackPressed().
void org.cosmic.mobuzz.general.ui.UiProfileLogin.popdLogin (String title, String content, boolean resetdata) private
Definition at line 422 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.context.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.responseToResult().
void org.cosmic.mobuzz.general.ui.UiProfileLogin.popdNoInternet () private
Definition at line 372 of file UiProfileLogin.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.attemptLogin(), org.cosmic.mobuzz.general.ui.UiProfileLogin.forgotpwordTextView_Click(), and org.cosmic.mobuzz.general.ui.UiProfileLogin.registerTextView_Click().
void org.cosmic.mobuzz.general.ui.UiProfileLogin.popdRequestFailed (String title, String content) private
Definition at line 442 of file UiProfileLogin.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.responseToResult().
void org.cosmic.mobuzz.general.ui.UiProfileLogin.registerTextView_Click () private
Definition at line 145 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.context, org.cosmic.mobuzz.general.ui.UiProfileLogin.isNetworkAvailable(), and org.cosmic.mobuzz.general.ui.UiProfileLogin.popdNoInternet().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.onCreate().
void org.cosmic.mobuzz.general.ui.UiProfileLogin.responseToResult (String result)
Definition at line 249 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.context, org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getLanguage(), org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getStatus(), org.cosmic.mobuzz.general.ui.UiProfileLogin.makeLogin(), org.cosmic.mobuzz.general.ui.UiProfileLogin.popdLogin(), org.cosmic.mobuzz.general.ui.UiProfileLogin.popdRequestFailed(), org.cosmic.mobuzz.general.ui.UiProfileLogin.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.LoginTask.onPostExecute().
void org.cosmic.mobuzz.general.ui.UiProfileLogin.signinButton_Click () private
Definition at line 116 of file UiProfileLogin.java.
References org.cosmic.mobuzz.general.ui.UiProfileLogin.login().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.onCreate().
Member Data Documentation
final Context org.cosmic.mobuzz.general.ui.UiProfileLogin.context = UiProfileLogin.this private
Definition at line 46 of file UiProfileLogin.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.forgotpwordTextView_Click(), org.cosmic.mobuzz.general.ui.UiProfileLogin.isNetworkAvailable(), org.cosmic.mobuzz.general.ui.UiProfileLogin.loginTask(), org.cosmic.mobuzz.general.ui.UiProfileLogin.makeLogin(), org.cosmic.mobuzz.general.ui.UiProfileLogin.onCreate(), org.cosmic.mobuzz.general.ui.UiProfileLogin.onPause(), org.cosmic.mobuzz.general.ui.UiProfileLogin.LoginTask.onPreExecute(), org.cosmic.mobuzz.general.ui.UiProfileLogin.onResume(), org.cosmic.mobuzz.general.ui.UiProfileLogin.popdExit(), org.cosmic.mobuzz.general.ui.UiProfileLogin.popdLogin(), org.cosmic.mobuzz.general.ui.UiProfileLogin.registerTextView_Click(), and org.cosmic.mobuzz.general.ui.UiProfileLogin.responseToResult().
Dialog org.cosmic.mobuzz.general.ui.UiProfileLogin.progressDialog private
Definition at line 49 of file UiProfileLogin.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.LoginTask.onPostExecute(), and org.cosmic.mobuzz.general.ui.UiProfileLogin.LoginTask.onPreExecute().
TextView org.cosmic.mobuzz.general.ui.UiProfileLogin.registerTextView private
Definition at line 51 of file UiProfileLogin.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.onCreate().
Button org.cosmic.mobuzz.general.ui.UiProfileLogin.signinButton private
Definition at line 50 of file UiProfileLogin.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.onCreate().
String org.cosmic.mobuzz.general.ui.UiProfileLogin.TAG = UiProfileLogin.class.getName() private
Definition at line 47 of file UiProfileLogin.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.onCreate(), org.cosmic.mobuzz.general.ui.UiProfileLogin.onPause(), org.cosmic.mobuzz.general.ui.UiProfileLogin.onResume(), org.cosmic.mobuzz.general.ui.UiProfileLogin.popdExit(), and org.cosmic.mobuzz.general.ui.UiProfileLogin.responseToResult().
String org.cosmic.mobuzz.general.ui.UiProfileLogin.url_profile_login private
Definition at line 52 of file UiProfileLogin.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.loginTask(), and org.cosmic.mobuzz.general.ui.UiProfileLogin.onCreate().
EditText org.cosmic.mobuzz.general.ui.UiProfileLogin.usernameET private
Definition at line 48 of file UiProfileLogin.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.onCreate().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiProfileLogin.java