Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.FormUpload Class Reference
org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.FormUpload Class Reference
Inherits AsyncTask< String, Void, String >.
Public Member Functions
FormUpload (String url_report_submit, Bitmap bitmap, String[] data)
Protected Member Functions
void onPreExecute ()
String doInBackground (String...formdata)
void onPostExecute (String result)
Detailed Description
Definition at line 825 of file UiBreedingsiteSubpageReport.java.
Constructor & Destructor Documentation
org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.FormUpload.FormUpload (String url_report_submit, Bitmap bitmap, String[] data)
Definition at line 834 of file UiBreedingsiteSubpageReport.java.
Member Function Documentation
String org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.FormUpload.doInBackground (String... formdata) protected
Definition at line 859 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.bitmapToString().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.FormUpload.onPostExecute (String result) protected
Definition at line 883 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.CONN_EXCEPTION, org.cosmic.mobuzz.general.pojo.ResponsePojo.getResponseCode(), org.cosmic.mobuzz.general.pojo.ResponsePojo.getResponseContent(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.noRetry, org.cosmic.mobuzz.general.util.GlobalVariables.OTHER_EXCEPTION, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdRequestFailed(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popupContent(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.responseToResult().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.FormUpload.onPreExecute () protected
Definition at line 841 of file UiBreedingsiteSubpageReport.java.
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiBreedingsiteSubpageReport.java