Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiHome Class Reference
org.cosmic.mobuzz.general.ui.UiHome Class Reference
Inherits Fragment.
Public Member Functions
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onResume ()
void onPause ()
Private Member Functions
void breedingsite ()
void informationmap ()
void aboutdengue ()
boolean isNetworkAvailable ()
void popdNoInternet ()
Private Attributes
final String TAG = UiHome.class.getName()
Detailed Description
Definition at line 21 of file UiHome.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiHome.aboutdengue () private
Definition at line 99 of file UiHome.java.
Referenced by org.cosmic.mobuzz.general.ui.UiHome.onCreateView().
void org.cosmic.mobuzz.general.ui.UiHome.breedingsite () private
Definition at line 66 of file UiHome.java.
Referenced by org.cosmic.mobuzz.general.ui.UiHome.onCreateView().
void org.cosmic.mobuzz.general.ui.UiHome.informationmap () private
Definition at line 81 of file UiHome.java.
References org.cosmic.mobuzz.general.ui.UiHome.isNetworkAvailable(), and org.cosmic.mobuzz.general.ui.UiHome.popdNoInternet().
Referenced by org.cosmic.mobuzz.general.ui.UiHome.onCreateView().
boolean org.cosmic.mobuzz.general.ui.UiHome.isNetworkAvailable () private
Definition at line 115 of file UiHome.java.
Referenced by org.cosmic.mobuzz.general.ui.UiHome.informationmap().
View org.cosmic.mobuzz.general.ui.UiHome.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 30 of file UiHome.java.
References org.cosmic.mobuzz.general.ui.UiHome.aboutdengue(), org.cosmic.mobuzz.general.ui.UiHome.breedingsite(), org.cosmic.mobuzz.general.ui.UiHome.informationmap(), and org.cosmic.mobuzz.general.ui.UiHome.TAG.
void org.cosmic.mobuzz.general.ui.UiHome.onPause ()
Definition at line 57 of file UiHome.java.
References org.cosmic.mobuzz.general.ui.UiHome.TAG.
void org.cosmic.mobuzz.general.ui.UiHome.onResume ()
Definition at line 51 of file UiHome.java.
References org.cosmic.mobuzz.general.ui.UiHome.TAG.
void org.cosmic.mobuzz.general.ui.UiHome.popdNoInternet () private
Definition at line 126 of file UiHome.java.
Referenced by org.cosmic.mobuzz.general.ui.UiHome.informationmap().
Member Data Documentation
final String org.cosmic.mobuzz.general.ui.UiHome.TAG = UiHome.class.getName() private
Definition at line 27 of file UiHome.java.
Referenced by org.cosmic.mobuzz.general.ui.UiHome.onCreateView(), org.cosmic.mobuzz.general.ui.UiHome.onPause(), and org.cosmic.mobuzz.general.ui.UiHome.onResume().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiHome.java