Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic Class Reference
org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic Class Reference
Inherits Activity.
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
void onResume ()
void onPause ()
void onBackPressed ()
void onDestroy ()
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Attributes
Typeface font
final String TAG = UiAboutMobuzzCosmic.class.getName()
Detailed Description
Definition at line 18 of file UiAboutMobuzzCosmic.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.onBackPressed ()
Definition at line 77 of file UiAboutMobuzzCosmic.java.
References org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.TAG.
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.onCreate (Bundle savedInstanceState) protected
Definition at line 27 of file UiAboutMobuzzCosmic.java.
References org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.font, org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, org.cosmic.mobuzz.general.util.LogAction.START, and org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.TAG.
boolean org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.onCreateOptionsMenu (Menu menu)
Definition at line 60 of file UiAboutMobuzzCosmic.java.
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.onDestroy ()
Definition at line 84 of file UiAboutMobuzzCosmic.java.
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.onPause ()
Definition at line 71 of file UiAboutMobuzzCosmic.java.
References org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.TAG.
void org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.onResume ()
Definition at line 65 of file UiAboutMobuzzCosmic.java.
References org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.TAG.
Member Data Documentation
Typeface org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.font private
Definition at line 21 of file UiAboutMobuzzCosmic.java.
Referenced by org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.onCreate().
final String org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.TAG = UiAboutMobuzzCosmic.class.getName() private
Definition at line 22 of file UiAboutMobuzzCosmic.java.
Referenced by org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.onBackPressed(), org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.onCreate(), org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.onPause(), and org.cosmic.mobuzz.general.ui.UiAboutMobuzzCosmic.onResume().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiAboutMobuzzCosmic.java