Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport Class Reference
org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport Class Reference
Inherits Fragment.
Classes
class FormUpload
Public Member Functions
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onResume ()
void onPause ()
void onSaveInstanceState (Bundle outState)
void onActivityCreated (Bundle savedInstanceState)
void setUserVisibleHint (boolean isFragmentVisible)
void onActivityResult (int requestCode, int resultCode, Intent data)
String bitmapToString (Bitmap bitmap)
String getRealPathFromURI (Uri contentUri)
void responseToResult (String result)
Protected Member Functions
void attemptUpload ()
Private Member Functions
void setUploadEnable (boolean isEnable)
void getGPSCoordinates ()
void btn_location_Click ()
void setUpMap ()
void onGoogleMap (int resultCode, Intent data)
void btn_assessment_Click ()
void showAssessment ()
void btn_submit_Click ()
void uploadTask ()
void btn_camera_Click ()
void btn_gallery_Click ()
void onGalleryPhoto (int resultCode, Intent data)
void setGalleryImageUri (Uri uri)
void setImageResize ()
void dispatchTakePictureIntent ()
void onCameraPhoto (int resultCode, Intent data)
File createImageFile () throws IOException
boolean galleryAddCameraPic ()
void galleryLoadCameraPic ()
Bitmap rotateBitmap (Bitmap bitmap, String path)
int exifToDegrees (int exifOrientation)
void clearData ()
void clearMemory ()
boolean isNetworkAvailable ()
void popdNoInternet ()
void successUpload (boolean isSuccess)
void popupContent (String title, String content, int buttonAction)
void popdNoGPS (String content, boolean isExit)
void popdUnclearGPS (String content)
void popdListrAssessment ()
void popdRequestFailed (String title, String content)
void popdReauth (String title, String content)
Private Attributes
final String TAG = UiBreedingsiteSubpageReport.class.getName()
String url_report_submit
Typeface font
Double latitude
Double longitude
int noRetry = 0
SupportMapFragment mMapFragment
GoogleMap mMap
LatLng latLng
boolean isFirst = false
CMCRegions cmcRegions
Detailed Description
Definition at line 81 of file UiBreedingsiteSubpageReport.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.attemptUpload () protected
Definition at line 503 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.isNetworkAvailable(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdNoInternet(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.uploadTask().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_submit_Click().
String org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.bitmapToString (Bitmap bitmap)
Definition at line 806 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.FormUpload.doInBackground().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_assessment_Click () private
Definition at line 478 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.showAssessment().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCreateView().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_camera_Click () private
Definition at line 561 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.dispatchTakePictureIntent().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCreateView().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_gallery_Click () private
Definition at line 571 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.GALLERY_PHOTO_CODE.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCreateView().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_location_Click () private
Definition at line 340 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.GOOGLE_MAP_CODE.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCreateView().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_submit_Click () private
Definition at line 493 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.attemptUpload().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCreateView().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.clearData () private
Definition at line 1004 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.clearMemory().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.successUpload().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.clearMemory () private
Definition at line 1013 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.clearData(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.galleryLoadCameraPic(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setGalleryImageUri(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setImageResize().
File org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.createImageFile () throws IOException private
Definition at line 719 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.dispatchTakePictureIntent().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.dispatchTakePictureIntent () private
Definition at line 689 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.createImageFile(), org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.TAG, and org.cosmic.mobuzz.general.util.GlobalVariables.TAKE_PHOTO_CODE.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_camera_Click().
int org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.exifToDegrees (int exifOrientation) private
Definition at line 795 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.rotateBitmap().
boolean org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.galleryAddCameraPic () private
Definition at line 734 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCameraPhoto().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.galleryLoadCameraPic () private
Definition at line 744 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.clearMemory(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.rotateBitmap(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onActivityCreated(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCameraPhoto().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.getGPSCoordinates () private
Definition at line 307 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.cmcRegions, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.isFirst, org.cosmic.mobuzz.general.util.CMCRegions.isInCMC(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.latitude, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.longitude, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdNoGPS(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdUnclearGPS(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUploadEnable().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUpMap().
String org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.getRealPathFromURI (Uri contentUri)
Definition at line 814 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setGalleryImageUri().
boolean org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.isNetworkAvailable () private
Definition at line 1024 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.attemptUpload().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onActivityCreated (Bundle savedInstanceState)
Definition at line 218 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.galleryLoadCameraPic(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onActivityResult (int requestCode, int resultCode, Intent data)
Definition at line 254 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCameraPhoto(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGalleryPhoto(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGoogleMap().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCameraPhoto (int resultCode, Intent data) private
Definition at line 711 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.galleryAddCameraPic(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.galleryLoadCameraPic().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onActivityResult().
View org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 115 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_assessment_Click(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_camera_Click(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_gallery_Click(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_location_Click(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_submit_Click(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.cmcRegions, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.font, org.cosmic.mobuzz.general.util.GlobalVariables.GPS_COLOMBO, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.latLng, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUploadEnable(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUpMap(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.url_report_submit.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGalleryPhoto (int resultCode, Intent data) private
Parameters
resultCode
data
       Returns result from the gallery action.
Definition at line 587 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setGalleryImageUri(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.TAG.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onActivityResult().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGoogleMap (int resultCode, Intent data) private
Definition at line 431 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.cmcRegions, org.cosmic.mobuzz.general.util.CMCRegions.isInCMC(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.latitude, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.latLng, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.longitude, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdUnclearGPS(), org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUploadEnable(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onActivityResult().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onPause ()
Definition at line 191 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.mMap, and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.TAG.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onResume ()
Definition at line 179 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.mMap, and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.TAG.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onSaveInstanceState (Bundle outState)
Definition at line 210 of file UiBreedingsiteSubpageReport.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdListrAssessment () private
Definition at line 1149 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.showAssessment().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdNoGPS (String content, boolean isExit) private
Definition at line 1090 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUploadEnable().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.getGPSCoordinates().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdNoInternet () private
Definition at line 1035 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.attemptUpload().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdReauth (String title, String content) private
Definition at line 1205 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.responseToResult().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdRequestFailed (String title, String content) private
Definition at line 1198 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.FormUpload.onPostExecute(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.responseToResult(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUpMap().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdUnclearGPS (String content) private
Definition at line 1121 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUploadEnable().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.getGPSCoordinates(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGoogleMap().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popupContent (String title, String content, int buttonAction) private
Definition at line 1066 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setImageResize().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.FormUpload.onPostExecute(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.responseToResult(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.uploadTask().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.responseToResult (String result)
Definition at line 926 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getStatus(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdReauth(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdRequestFailed(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popupContent(), org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.successUpload(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.FormUpload.onPostExecute().
Bitmap org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.rotateBitmap (Bitmap bitmap, String path) private
Definition at line 771 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.exifToDegrees(), org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.TAG.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.galleryLoadCameraPic(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setGalleryImageUri(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setImageResize().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setGalleryImageUri (Uri uri) private
Parameters
uri
       Assigning image uri to the interface image view.
Definition at line 612 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.clearMemory(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.getRealPathFromURI(), org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.rotateBitmap(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGalleryPhoto().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setImageResize () private
Definition at line 655 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.clearMemory(), org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.rotateBitmap(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.TAG, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.uploadTask(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popupContent().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUploadEnable (boolean isEnable) private
Definition at line 271 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.getGPSCoordinates(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCreateView(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGoogleMap(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdNoGPS(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdUnclearGPS().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUpMap () private
Definition at line 356 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.getGPSCoordinates(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.mMap, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdRequestFailed(), org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.TAG.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCreateView().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUserVisibleHint (boolean isFragmentVisible)
Definition at line 230 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.mMap, and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.TAG.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.showAssessment () private
Definition at line 489 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popdListrAssessment().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.btn_assessment_Click().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.successUpload (boolean isSuccess) private
Definition at line 1042 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.clearData().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.responseToResult().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.uploadTask () private
Definition at line 512 of file UiBreedingsiteSubpageReport.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.latitude, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.longitude, org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.popupContent(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.url_report_submit, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.attemptUpload(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setImageResize().
Member Data Documentation
CMCRegions org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.cmcRegions private
Definition at line 111 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.getGPSCoordinates(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCreateView(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGoogleMap().
Typeface org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.font private
Definition at line 98 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCreateView().
boolean org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.isFirst = false private
Definition at line 110 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.getGPSCoordinates().
Double org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.latitude private
Definition at line 103 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.getGPSCoordinates(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGoogleMap(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.uploadTask().
LatLng org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.latLng private
Definition at line 109 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCreateView(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGoogleMap().
Double org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.longitude private
Definition at line 104 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.getGPSCoordinates(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGoogleMap(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.uploadTask().
GoogleMap org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.mMap private
Definition at line 108 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onPause(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onResume(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUpMap(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUserVisibleHint().
SupportMapFragment org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.mMapFragment private
Definition at line 107 of file UiBreedingsiteSubpageReport.java.
int org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.noRetry = 0 private
Definition at line 106 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.FormUpload.onPostExecute().
final String org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.TAG = UiBreedingsiteSubpageReport.class.getName() private
Definition at line 96 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.dispatchTakePictureIntent(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGalleryPhoto(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGoogleMap(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onPause(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onResume(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.responseToResult(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.rotateBitmap(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setGalleryImageUri(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setImageResize(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUpMap(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.setUserVisibleHint().
String org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.url_report_submit private
Definition at line 97 of file UiBreedingsiteSubpageReport.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onCreateView(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.uploadTask().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiBreedingsiteSubpageReport.java