Mo-BuzzPHI: org.cosmic.mobuzz.general.util.CMCRegions Class Reference
org.cosmic.mobuzz.general.util.CMCRegions Class Reference
Public Member Functions
CMCRegions ()
List< LatLng > getCMCWard (int wardNo)
String[][] getMohDetails ()
LatLng getMohLocation (int i)
LatLng getMohLocation (String strlatlng)
String getMohDetItem (int i, int j)
List< LatLng > getCMCMoh (int mohNo)
List< LatLng > getCMCRegion ()
boolean isInCMC (LatLng location)
Private Member Functions
List< LatLng > stringToLatLng (String strWards)
Private Attributes
final String TAG = CMCRegions.class.getName()
String[] strCmcWards = new String[48]
String[] strCmcMOHs = new String[7]
String cmcBoundry = "79.8736632,6.979964; 79.872129,6.9782708; 79.8713136,6.9785903; 79.8707557,6.9784625; 79.8696613,6.9770781; 79.8695648,6.9754168; 79.8689318,6.9739365; 79.8683417,6.9739471; 79.8681378,6.97301; 79.8688352,6.9728609; 79.8688674,6.9717214; 79.8684168,6.9708375; 79.8678267,6.9708854; 79.8677301,6.9704009; 79.8685455,6.9699003; 79.8677731,6.968239; 79.8664212,6.9685585; 79.8667002,6.9679728; 79.8655415,6.9668652; 79.864769,6.9655127; 79.8634815,6.9650015; 79.8623443,6.9647459; 79.8622048,6.9637342; 79.8617971,6.9636703; 79.8609495,6.9633189; 79.8591095,6.9633348; 79.8593724,6.9645649; 79.85919,6.964895; 79.8588467,6.9637928; 79.8587179,6.9627651; 79.8576879,6.962158; 79.8564005,6.9618918; 79.8560143,6.9614445; 79.8532248,6.9612741; 79.8532677,6.9605499; 79.85654,6.960731; 79.8565292,6.9595382; 79.8531175,6.9589631; 79.853096,6.9576106; 79.8564863,6.9582496; 79.8564541,6.957355; 79.8539972,6.9568225; 79.8540831,6.956535; 79.8573875,6.9566308; 79.8554671,6.9559119; 79.8556495,6.9552144; 79.8562288,6.9550546; 79.8561215,6.9545008; 79.8537612,6.9546819; 79.8535788,6.9534891; 79.8525274,6.9480682; 79.8498666,6.9424876; 79.8518836,6.9414439; 79.8509932,6.9407622; 79.8493624,6.9414811; 79.8504996,6.9403575; 79.8476458,6.9382168; 79.8463798,6.9382488; 79.8473454,6.942019; 79.8462939,6.9422426; 79.8452425,6.9387281; 79.8436546,6.939186; 79.8430109,6.9398996; 79.8445612,6.9406611; 79.8450172,6.9423278; 79.8468518,6.9530098; 79.8445666,6.9534784; 79.8435366,6.9469207; 79.8430109,6.9466677; 79.8426676,6.9451395; 79.8418736,6.9453525; 79.8418307,6.9459382; 79.8403716,6.9464388; 79.8407793,6.9496657; 79.8401678,6.9496551; 79.8396796,6.9464601; 79.8391378,6.9445324; 79.8374212,6.9452247; 79.8369813,6.9452779; 79.8351037,6.9439094; 79.8341328,6.9435526; 79.8331618,6.9448093; 79.8283017,6.9448093; 79.8259306,6.9443194; 79.8255658,6.9434674; 79.8239458,6.9446496; 79.8232269,6.9464707; 79.8232055,6.9572272; 79.8297768,6.96387; 79.8295328,6.9641376; 79.8312467,6.9657417; 79.8309356,6.9660558; 79.8225403,6.9574402; 79.8225403,6.9446389; 79.8232055,6.9430627; 79.8254156,6.94138; 79.8365414,6.9411403; 79.8393953,6.9398037; 79.8402375,6.9381583; 79.8399907,6.9362891; 79.8408115,6.9352294; 79.8408866,6.9336692; 79.8424315,6.9295741; 79.8492014,6.906936; 79.8534393,6.891151; 79.8593831,6.8644792; 79.8594046,6.8626471; 79.8626339,6.8624448; 79.8648977,6.8643088; 79.8643613,6.8652249; 79.8643076,6.8660877; 79.8657346,6.8679518; 79.8653913,6.8695922; 79.8662066,6.8714669; 79.867537,6.8715947; 79.8688889,6.8726812; 79.8715067,6.8735759; 79.8727512,6.8736612; 79.8782444,6.8701887; 79.881506,6.8689957; 79.8823643,6.8689531; 79.8834693,6.87021; 79.8866236,6.8720847; 79.8872995,6.8719036; 79.8882222,6.8734801; 79.885025,6.8776662; 79.8844671,6.8823316; 79.8844242,6.8845258; 79.8824716,6.887849; 79.8835874,6.8889568; 79.8839092,6.8901923; 79.8847461,6.8925782; 79.8832655,6.8981382; 79.8824716,6.900098; 79.8841023,6.9019726; 79.8862052,6.9049123; 79.8872781,6.9052744; 79.8874068,6.907362; 79.8885226,6.9093644; 79.8892951,6.9100673; 79.8890162,6.9131135; 79.8901963,6.9145194; 79.8895955,6.9158614; 79.8877287,6.9161809; 79.8867416,6.9164791; 79.8865271,6.9168839; 79.8869133,6.9201217; 79.8860121,6.9219536; 79.8861408,6.9244671; 79.8857814,6.9253192; 79.8848534,6.9253991; 79.884038,6.9258411; 79.8836625,6.9273641; 79.8838234,6.9281842; 79.884553,6.9287487; 79.8830724,6.9315551; 79.8819458,6.9330621; 79.8814577,6.9351229; 79.881573,6.935722; 79.8836517,6.9386322; 79.8836571,6.9388026; 79.8822087,6.9400061; 79.8818922,6.9411244; 79.8815703,6.941806; 79.8808461,6.9424077; 79.8792046,6.9427858; 79.8787969,6.9433982; 79.8783302,6.9433183; 79.8784804,6.9504112; 79.8746727,6.9509833; 79.8748487,6.9521392; 79.8756721,6.9530404; 79.8763893,6.9543447; 79.8772071,6.9554407; 79.8773646,6.9558533; 79.8780464,6.9569415; 79.8788774,6.9579088; 79.877826,6.9604647; 79.8781157,6.9645649; 79.8824179,6.9701879; 79.8841131,6.9739045; 79.8840165,6.9772059; 79.8821604,6.9795061; 79.8789954,6.9805817; 79.8736632,6.979964"
Detailed Description
Definition at line 11 of file CMCRegions.java.
Constructor & Destructor Documentation
org.cosmic.mobuzz.general.util.CMCRegions.CMCRegions ()
Definition at line 28 of file CMCRegions.java.
References org.cosmic.mobuzz.general.util.CMCRegions.strCmcMOHs, and org.cosmic.mobuzz.general.util.CMCRegions.strCmcWards.
Member Function Documentation
List<LatLng> org.cosmic.mobuzz.general.util.CMCRegions.getCMCMoh (int mohNo)
Definition at line 177 of file CMCRegions.java.
References org.cosmic.mobuzz.general.util.CMCRegions.strCmcMOHs, and org.cosmic.mobuzz.general.util.CMCRegions.stringToLatLng().
List<LatLng> org.cosmic.mobuzz.general.util.CMCRegions.getCMCRegion ()
Definition at line 190 of file CMCRegions.java.
References org.cosmic.mobuzz.general.util.CMCRegions.cmcBoundry, and org.cosmic.mobuzz.general.util.CMCRegions.stringToLatLng().
Referenced by org.cosmic.mobuzz.general.util.CMCRegions.isInCMC().
List<LatLng> org.cosmic.mobuzz.general.util.CMCRegions.getCMCWard (int wardNo)
Definition at line 126 of file CMCRegions.java.
References org.cosmic.mobuzz.general.util.CMCRegions.strCmcWards, and org.cosmic.mobuzz.general.util.CMCRegions.stringToLatLng().
String [][] org.cosmic.mobuzz.general.util.CMCRegions.getMohDetails ()
Definition at line 137 of file CMCRegions.java.
String org.cosmic.mobuzz.general.util.CMCRegions.getMohDetItem (int i, int j)
Definition at line 171 of file CMCRegions.java.
LatLng org.cosmic.mobuzz.general.util.CMCRegions.getMohLocation (int i)
Definition at line 143 of file CMCRegions.java.
LatLng org.cosmic.mobuzz.general.util.CMCRegions.getMohLocation (String strlatlng)
Definition at line 148 of file CMCRegions.java.
boolean org.cosmic.mobuzz.general.util.CMCRegions.isInCMC (LatLng location)
Definition at line 197 of file CMCRegions.java.
References org.cosmic.mobuzz.general.util.CMCRegions.getCMCRegion().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.getGPSCoordinates(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.onGoogleMap(), and org.cosmic.mobuzz.general.ui.UiGoogleMap.setUpMap().
List<LatLng> org.cosmic.mobuzz.general.util.CMCRegions.stringToLatLng (String strWards) private
Definition at line 93 of file CMCRegions.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.util.CMCRegions.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.util.CMCRegions.getCMCMoh(), org.cosmic.mobuzz.general.util.CMCRegions.getCMCRegion(), and org.cosmic.mobuzz.general.util.CMCRegions.getCMCWard().
Member Data Documentation
String org.cosmic.mobuzz.general.util.CMCRegions.cmcBoundry = "79.8736632,6.979964; 79.872129,6.9782708; 79.8713136,6.9785903; 79.8707557,6.9784625; 79.8696613,6.9770781; 79.8695648,6.9754168; 79.8689318,6.9739365; 79.8683417,6.9739471; 79.8681378,6.97301; 79.8688352,6.9728609; 79.8688674,6.9717214; 79.8684168,6.9708375; 79.8678267,6.9708854; 79.8677301,6.9704009; 79.8685455,6.9699003; 79.8677731,6.968239; 79.8664212,6.9685585; 79.8667002,6.9679728; 79.8655415,6.9668652; 79.864769,6.9655127; 79.8634815,6.9650015; 79.8623443,6.9647459; 79.8622048,6.9637342; 79.8617971,6.9636703; 79.8609495,6.9633189; 79.8591095,6.9633348; 79.8593724,6.9645649; 79.85919,6.964895; 79.8588467,6.9637928; 79.8587179,6.9627651; 79.8576879,6.962158; 79.8564005,6.9618918; 79.8560143,6.9614445; 79.8532248,6.9612741; 79.8532677,6.9605499; 79.85654,6.960731; 79.8565292,6.9595382; 79.8531175,6.9589631; 79.853096,6.9576106; 79.8564863,6.9582496; 79.8564541,6.957355; 79.8539972,6.9568225; 79.8540831,6.956535; 79.8573875,6.9566308; 79.8554671,6.9559119; 79.8556495,6.9552144; 79.8562288,6.9550546; 79.8561215,6.9545008; 79.8537612,6.9546819; 79.8535788,6.9534891; 79.8525274,6.9480682; 79.8498666,6.9424876; 79.8518836,6.9414439; 79.8509932,6.9407622; 79.8493624,6.9414811; 79.8504996,6.9403575; 79.8476458,6.9382168; 79.8463798,6.9382488; 79.8473454,6.942019; 79.8462939,6.9422426; 79.8452425,6.9387281; 79.8436546,6.939186; 79.8430109,6.9398996; 79.8445612,6.9406611; 79.8450172,6.9423278; 79.8468518,6.9530098; 79.8445666,6.9534784; 79.8435366,6.9469207; 79.8430109,6.9466677; 79.8426676,6.9451395; 79.8418736,6.9453525; 79.8418307,6.9459382; 79.8403716,6.9464388; 79.8407793,6.9496657; 79.8401678,6.9496551; 79.8396796,6.9464601; 79.8391378,6.9445324; 79.8374212,6.9452247; 79.8369813,6.9452779; 79.8351037,6.9439094; 79.8341328,6.9435526; 79.8331618,6.9448093; 79.8283017,6.9448093; 79.8259306,6.9443194; 79.8255658,6.9434674; 79.8239458,6.9446496; 79.8232269,6.9464707; 79.8232055,6.9572272; 79.8297768,6.96387; 79.8295328,6.9641376; 79.8312467,6.9657417; 79.8309356,6.9660558; 79.8225403,6.9574402; 79.8225403,6.9446389; 79.8232055,6.9430627; 79.8254156,6.94138; 79.8365414,6.9411403; 79.8393953,6.9398037; 79.8402375,6.9381583; 79.8399907,6.9362891; 79.8408115,6.9352294; 79.8408866,6.9336692; 79.8424315,6.9295741; 79.8492014,6.906936; 79.8534393,6.891151; 79.8593831,6.8644792; 79.8594046,6.8626471; 79.8626339,6.8624448; 79.8648977,6.8643088; 79.8643613,6.8652249; 79.8643076,6.8660877; 79.8657346,6.8679518; 79.8653913,6.8695922; 79.8662066,6.8714669; 79.867537,6.8715947; 79.8688889,6.8726812; 79.8715067,6.8735759; 79.8727512,6.8736612; 79.8782444,6.8701887; 79.881506,6.8689957; 79.8823643,6.8689531; 79.8834693,6.87021; 79.8866236,6.8720847; 79.8872995,6.8719036; 79.8882222,6.8734801; 79.885025,6.8776662; 79.8844671,6.8823316; 79.8844242,6.8845258; 79.8824716,6.887849; 79.8835874,6.8889568; 79.8839092,6.8901923; 79.8847461,6.8925782; 79.8832655,6.8981382; 79.8824716,6.900098; 79.8841023,6.9019726; 79.8862052,6.9049123; 79.8872781,6.9052744; 79.8874068,6.907362; 79.8885226,6.9093644; 79.8892951,6.9100673; 79.8890162,6.9131135; 79.8901963,6.9145194; 79.8895955,6.9158614; 79.8877287,6.9161809; 79.8867416,6.9164791; 79.8865271,6.9168839; 79.8869133,6.9201217; 79.8860121,6.9219536; 79.8861408,6.9244671; 79.8857814,6.9253192; 79.8848534,6.9253991; 79.884038,6.9258411; 79.8836625,6.9273641; 79.8838234,6.9281842; 79.884553,6.9287487; 79.8830724,6.9315551; 79.8819458,6.9330621; 79.8814577,6.9351229; 79.881573,6.935722; 79.8836517,6.9386322; 79.8836571,6.9388026; 79.8822087,6.9400061; 79.8818922,6.9411244; 79.8815703,6.941806; 79.8808461,6.9424077; 79.8792046,6.9427858; 79.8787969,6.9433982; 79.8783302,6.9433183; 79.8784804,6.9504112; 79.8746727,6.9509833; 79.8748487,6.9521392; 79.8756721,6.9530404; 79.8763893,6.9543447; 79.8772071,6.9554407; 79.8773646,6.9558533; 79.8780464,6.9569415; 79.8788774,6.9579088; 79.877826,6.9604647; 79.8781157,6.9645649; 79.8824179,6.9701879; 79.8841131,6.9739045; 79.8840165,6.9772059; 79.8821604,6.9795061; 79.8789954,6.9805817; 79.8736632,6.979964" private
Definition at line 188 of file CMCRegions.java.
Referenced by org.cosmic.mobuzz.general.util.CMCRegions.getCMCRegion().
String [] org.cosmic.mobuzz.general.util.CMCRegions.strCmcMOHs = new String[7] private
Definition at line 16 of file CMCRegions.java.
Referenced by org.cosmic.mobuzz.general.util.CMCRegions.CMCRegions(), and org.cosmic.mobuzz.general.util.CMCRegions.getCMCMoh().
String [] org.cosmic.mobuzz.general.util.CMCRegions.strCmcWards = new String[48] private
Definition at line 15 of file CMCRegions.java.
Referenced by org.cosmic.mobuzz.general.util.CMCRegions.CMCRegions(), and org.cosmic.mobuzz.general.util.CMCRegions.getCMCWard().
final String org.cosmic.mobuzz.general.util.CMCRegions.TAG = CMCRegions.class.getName() private
Definition at line 13 of file CMCRegions.java.
Referenced by org.cosmic.mobuzz.general.util.CMCRegions.stringToLatLng().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/util/CMCRegions.java