Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiEducation Class Reference
org.cosmic.mobuzz.general.ui.UiEducation Class Reference
Inherits Activity.
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
void onResume ()
void onPause ()
void onBackPressed ()
void onDestroy ()
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
void EducationPages_Click ()
void rdg_main_navigation ()
void but_home ()
void but_profile ()
void but_info ()
Private Attributes
final String TAG = UiEducation.class.getName()
Detailed Description
Definition at line 21 of file UiEducation.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiEducation.but_home () private
Definition at line 184 of file UiEducation.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducation.rdg_main_navigation().
void org.cosmic.mobuzz.general.ui.UiEducation.but_info () private
Definition at line 201 of file UiEducation.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducation.rdg_main_navigation().
void org.cosmic.mobuzz.general.ui.UiEducation.but_profile () private
Definition at line 192 of file UiEducation.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducation.rdg_main_navigation().
void org.cosmic.mobuzz.general.ui.UiEducation.EducationPages_Click () private
Definition at line 96 of file UiEducation.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducation.onCreate().
void org.cosmic.mobuzz.general.ui.UiEducation.onBackPressed ()
Definition at line 84 of file UiEducation.java.
References org.cosmic.mobuzz.general.ui.UiEducation.TAG.
void org.cosmic.mobuzz.general.ui.UiEducation.onCreate (Bundle savedInstanceState) protected
Definition at line 31 of file UiEducation.java.
References org.cosmic.mobuzz.general.ui.UiEducation.EducationPages_Click(), org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, org.cosmic.mobuzz.general.ui.UiEducation.rdg_main_navigation(), org.cosmic.mobuzz.general.util.LogAction.START, and org.cosmic.mobuzz.general.ui.UiEducation.TAG.
boolean org.cosmic.mobuzz.general.ui.UiEducation.onCreateOptionsMenu (Menu menu)
Definition at line 67 of file UiEducation.java.
void org.cosmic.mobuzz.general.ui.UiEducation.onDestroy ()
Definition at line 91 of file UiEducation.java.
void org.cosmic.mobuzz.general.ui.UiEducation.onPause ()
Definition at line 78 of file UiEducation.java.
References org.cosmic.mobuzz.general.ui.UiEducation.TAG.
void org.cosmic.mobuzz.general.ui.UiEducation.onResume ()
Definition at line 72 of file UiEducation.java.
References org.cosmic.mobuzz.general.ui.UiEducation.TAG.
void org.cosmic.mobuzz.general.ui.UiEducation.rdg_main_navigation () private
Definition at line 155 of file UiEducation.java.
References org.cosmic.mobuzz.general.ui.UiEducation.but_home(), org.cosmic.mobuzz.general.ui.UiEducation.but_info(), and org.cosmic.mobuzz.general.ui.UiEducation.but_profile().
Referenced by org.cosmic.mobuzz.general.ui.UiEducation.onCreate().
Member Data Documentation
final String org.cosmic.mobuzz.general.ui.UiEducation.TAG = UiEducation.class.getName() private
Definition at line 23 of file UiEducation.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducation.onBackPressed(), org.cosmic.mobuzz.general.ui.UiEducation.onCreate(), org.cosmic.mobuzz.general.ui.UiEducation.onPause(), and org.cosmic.mobuzz.general.ui.UiEducation.onResume().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiEducation.java