Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiProfileRecover Class Reference
org.cosmic.mobuzz.general.ui.UiProfileRecover Class Reference
Inherits Activity.
Classes
class ResetTask
Public Member Functions
void onBackPressed ()
boolean onCreateOptionsMenu (Menu menu)
void onResume ()
void onPause ()
void doOnResult (String result)
Protected Member Functions
void onCreate (Bundle savedInstanceState)
void doReset ()
Private Member Functions
void resetBT_Click ()
boolean validate ()
void clear ()
String makeJstring ()
boolean isNetworkAvailable ()
void popdNoInternet ()
void resetPassword (String title, String content, boolean resetdata)
void popdRequestFailed (String title, String content)
Private Attributes
final Context context = UiProfileRecover.this
final String TAG = UiProfileRecover.class.getName()
EditText usernameET
Button resetBT
Dialog progressDialog
Typeface font
String url_profile_recover
Detailed Description
Definition at line 32 of file UiProfileRecover.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiProfileRecover.clear () private
Definition at line 143 of file UiProfileRecover.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.resetPassword().
void org.cosmic.mobuzz.general.ui.UiProfileRecover.doOnResult (String result)
Definition at line 205 of file UiProfileRecover.java.
References org.cosmic.mobuzz.general.ui.UiProfileRecover.popdRequestFailed(), org.cosmic.mobuzz.general.ui.UiProfileRecover.resetPassword(), org.cosmic.mobuzz.general.ui.UiProfileRecover.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.ResetTask.onPostExecute().
void org.cosmic.mobuzz.general.ui.UiProfileRecover.doReset () protected
Definition at line 109 of file UiProfileRecover.java.
References org.cosmic.mobuzz.general.ui.UiProfileRecover.makeJstring(), org.cosmic.mobuzz.general.ui.UiProfileRecover.url_profile_recover, and org.cosmic.mobuzz.general.ui.UiProfileRecover.validate().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.resetBT_Click().
boolean org.cosmic.mobuzz.general.ui.UiProfileRecover.isNetworkAvailable () private
Definition at line 232 of file UiProfileRecover.java.
References org.cosmic.mobuzz.general.ui.UiProfileRecover.context.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.resetBT_Click().
String org.cosmic.mobuzz.general.ui.UiProfileRecover.makeJstring () private
Definition at line 148 of file UiProfileRecover.java.
References org.cosmic.mobuzz.general.ui.UiProfileRecover.TAG.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.doReset().
void org.cosmic.mobuzz.general.ui.UiProfileRecover.onBackPressed ()
Definition at line 65 of file UiProfileRecover.java.
References org.cosmic.mobuzz.general.ui.UiProfileRecover.context, and org.cosmic.mobuzz.general.ui.UiProfileRecover.TAG.
void org.cosmic.mobuzz.general.ui.UiProfileRecover.onCreate (Bundle savedInstanceState) protected
Definition at line 44 of file UiProfileRecover.java.
References org.cosmic.mobuzz.general.ui.UiProfileRecover.context, org.cosmic.mobuzz.general.ui.UiProfileRecover.font, org.cosmic.mobuzz.general.ui.UiProfileRecover.resetBT, org.cosmic.mobuzz.general.ui.UiProfileRecover.resetBT_Click(), org.cosmic.mobuzz.general.util.LogAction.START, org.cosmic.mobuzz.general.ui.UiProfileRecover.TAG, org.cosmic.mobuzz.general.ui.UiProfileRecover.url_profile_recover, and org.cosmic.mobuzz.general.ui.UiProfileRecover.usernameET.
boolean org.cosmic.mobuzz.general.ui.UiProfileRecover.onCreateOptionsMenu (Menu menu)
Definition at line 73 of file UiProfileRecover.java.
void org.cosmic.mobuzz.general.ui.UiProfileRecover.onPause ()
Definition at line 84 of file UiProfileRecover.java.
References org.cosmic.mobuzz.general.ui.UiProfileRecover.context, and org.cosmic.mobuzz.general.ui.UiProfileRecover.TAG.
void org.cosmic.mobuzz.general.ui.UiProfileRecover.onResume ()
Definition at line 78 of file UiProfileRecover.java.
References org.cosmic.mobuzz.general.ui.UiProfileRecover.context, and org.cosmic.mobuzz.general.ui.UiProfileRecover.TAG.
void org.cosmic.mobuzz.general.ui.UiProfileRecover.popdNoInternet () private
Definition at line 243 of file UiProfileRecover.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.resetBT_Click().
void org.cosmic.mobuzz.general.ui.UiProfileRecover.popdRequestFailed (String title, String content) private
Definition at line 277 of file UiProfileRecover.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.doOnResult().
void org.cosmic.mobuzz.general.ui.UiProfileRecover.resetBT_Click () private
Definition at line 93 of file UiProfileRecover.java.
References org.cosmic.mobuzz.general.ui.UiProfileRecover.doReset(), org.cosmic.mobuzz.general.ui.UiProfileRecover.isNetworkAvailable(), and org.cosmic.mobuzz.general.ui.UiProfileRecover.popdNoInternet().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.onCreate().
void org.cosmic.mobuzz.general.ui.UiProfileRecover.resetPassword (String title, String content, boolean resetdata) private
Definition at line 250 of file UiProfileRecover.java.
References org.cosmic.mobuzz.general.ui.UiProfileRecover.clear().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.doOnResult().
boolean org.cosmic.mobuzz.general.ui.UiProfileRecover.validate () private
Definition at line 120 of file UiProfileRecover.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.doReset().
Member Data Documentation
final Context org.cosmic.mobuzz.general.ui.UiProfileRecover.context = UiProfileRecover.this private
Definition at line 34 of file UiProfileRecover.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.isNetworkAvailable(), org.cosmic.mobuzz.general.ui.UiProfileRecover.onBackPressed(), org.cosmic.mobuzz.general.ui.UiProfileRecover.onCreate(), org.cosmic.mobuzz.general.ui.UiProfileRecover.onPause(), org.cosmic.mobuzz.general.ui.UiProfileRecover.ResetTask.onPreExecute(), and org.cosmic.mobuzz.general.ui.UiProfileRecover.onResume().
Typeface org.cosmic.mobuzz.general.ui.UiProfileRecover.font private
Definition at line 39 of file UiProfileRecover.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.onCreate().
Dialog org.cosmic.mobuzz.general.ui.UiProfileRecover.progressDialog private
Definition at line 38 of file UiProfileRecover.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.ResetTask.onPostExecute(), and org.cosmic.mobuzz.general.ui.UiProfileRecover.ResetTask.onPreExecute().
Button org.cosmic.mobuzz.general.ui.UiProfileRecover.resetBT private
Definition at line 37 of file UiProfileRecover.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.onCreate().
final String org.cosmic.mobuzz.general.ui.UiProfileRecover.TAG = UiProfileRecover.class.getName() private
Definition at line 35 of file UiProfileRecover.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.doOnResult(), org.cosmic.mobuzz.general.ui.UiProfileRecover.makeJstring(), org.cosmic.mobuzz.general.ui.UiProfileRecover.onBackPressed(), org.cosmic.mobuzz.general.ui.UiProfileRecover.onCreate(), org.cosmic.mobuzz.general.ui.UiProfileRecover.onPause(), and org.cosmic.mobuzz.general.ui.UiProfileRecover.onResume().
String org.cosmic.mobuzz.general.ui.UiProfileRecover.url_profile_recover private
Definition at line 40 of file UiProfileRecover.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.doReset(), and org.cosmic.mobuzz.general.ui.UiProfileRecover.onCreate().
EditText org.cosmic.mobuzz.general.ui.UiProfileRecover.usernameET private
Definition at line 36 of file UiProfileRecover.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRecover.onCreate().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiProfileRecover.java