Mo-BuzzPHI: org.cosmic.mobuzz.general.network.MakeJsonString Class Reference
org.cosmic.mobuzz.general.network.MakeJsonString Class Reference
Public Member Functions
String forLogin (Context context, String userName, String password, String time_stamp)
String forRegister (Context context, String[] userData)
String forProfileUpdate (String[] userData)
String forFormSubmit (String[] userData)
String forFormSubmit (String strImage, String[] userData)
Private Member Functions
String getTimestamp ()
Detailed Description
Definition at line 10 of file MakeJsonString.java.
Member Function Documentation
String org.cosmic.mobuzz.general.network.MakeJsonString.forFormSubmit (String[] userData)
Definition at line 92 of file MakeJsonString.java.
String org.cosmic.mobuzz.general.network.MakeJsonString.forFormSubmit (String strImage, String[] userData)
Definition at line 122 of file MakeJsonString.java.
References org.cosmic.mobuzz.general.network.MakeJsonString.getTimestamp().
String org.cosmic.mobuzz.general.network.MakeJsonString.forLogin (Context context, String userName, String password, String time_stamp)
Definition at line 12 of file MakeJsonString.java.
String org.cosmic.mobuzz.general.network.MakeJsonString.forProfileUpdate (String[] userData)
Definition at line 66 of file MakeJsonString.java.
String org.cosmic.mobuzz.general.network.MakeJsonString.forRegister (Context context, String[] userData)
Definition at line 33 of file MakeJsonString.java.
References org.cosmic.mobuzz.general.network.MakeJsonString.getTimestamp().
String org.cosmic.mobuzz.general.network.MakeJsonString.getTimestamp () private
Definition at line 118 of file MakeJsonString.java.
Referenced by org.cosmic.mobuzz.general.network.MakeJsonString.forFormSubmit(), and org.cosmic.mobuzz.general.network.MakeJsonString.forRegister().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/network/MakeJsonString.java