Mo-BuzzPHI: org.cosmic.mobuzz.general.pojo.HistoryPojo Class Reference
org.cosmic.mobuzz.general.pojo.HistoryPojo Class Reference
Public Member Functions
HistoryPojo ()
HistoryPojo (int image, String id, String gps, String address, String date, String ward, String remarks, String assessment, String cmcmessage)
HistoryPojo (int image, String id, String gps, String address, String date, String ward, String remarks, String assessment, String cmcmessage, String imagepath)
String getId ()
void setId (String id)
String getGps ()
void setGps (String gps)
String getAddress ()
void setAddress (String address)
String getDate ()
void setDate (String date)
String getWard ()
void setWard (String ward)
String getRemarks ()
void setRemarks (String remarks)
String getAssessment ()
void setAssessment (String assessment)
String getCmcMessage ()
void setCmcMessage (String cmcMessage)
int getImage ()
void setImage (int image)
String getCmcmessage ()
void setCmcmessage (String cmcmessage)
String getImagepath ()
void setImagepath (String imagepath)
Detailed Description
Definition at line 5 of file HistoryPojo.java.
Constructor & Destructor Documentation
org.cosmic.mobuzz.general.pojo.HistoryPojo.HistoryPojo ()
Definition at line 18 of file HistoryPojo.java.
org.cosmic.mobuzz.general.pojo.HistoryPojo.HistoryPojo (int image, String id, String gps, String address, String date, String ward, String remarks, String assessment, String cmcmessage)
Definition at line 22 of file HistoryPojo.java.
org.cosmic.mobuzz.general.pojo.HistoryPojo.HistoryPojo (int image, String id, String gps, String address, String date, String ward, String remarks, String assessment, String cmcmessage, String imagepath)
Definition at line 35 of file HistoryPojo.java.
Member Function Documentation
String org.cosmic.mobuzz.general.pojo.HistoryPojo.getAddress ()
Definition at line 83 of file HistoryPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
String org.cosmic.mobuzz.general.pojo.HistoryPojo.getAssessment ()
Definition at line 151 of file HistoryPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
String org.cosmic.mobuzz.general.pojo.HistoryPojo.getCmcMessage ()
Definition at line 168 of file HistoryPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
String org.cosmic.mobuzz.general.pojo.HistoryPojo.getCmcmessage ()
Definition at line 194 of file HistoryPojo.java.
String org.cosmic.mobuzz.general.pojo.HistoryPojo.getDate ()
Definition at line 100 of file HistoryPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
String org.cosmic.mobuzz.general.pojo.HistoryPojo.getGps ()
Definition at line 66 of file HistoryPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
String org.cosmic.mobuzz.general.pojo.HistoryPojo.getId ()
Definition at line 49 of file HistoryPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
int org.cosmic.mobuzz.general.pojo.HistoryPojo.getImage ()
Definition at line 186 of file HistoryPojo.java.
String org.cosmic.mobuzz.general.pojo.HistoryPojo.getImagepath ()
Definition at line 202 of file HistoryPojo.java.
String org.cosmic.mobuzz.general.pojo.HistoryPojo.getRemarks ()
Definition at line 134 of file HistoryPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
String org.cosmic.mobuzz.general.pojo.HistoryPojo.getWard ()
Definition at line 117 of file HistoryPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
void org.cosmic.mobuzz.general.pojo.HistoryPojo.setAddress (String address)
Definition at line 96 of file HistoryPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryPojo.setAssessment (String assessment)
Definition at line 164 of file HistoryPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryPojo.setCmcMessage (String cmcMessage)
Definition at line 181 of file HistoryPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryPojo.setCmcmessage (String cmcmessage)
Definition at line 198 of file HistoryPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryPojo.setDate (String date)
Definition at line 113 of file HistoryPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryPojo.setGps (String gps)
Definition at line 79 of file HistoryPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryPojo.setId (String id)
Definition at line 62 of file HistoryPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryPojo.setImage (int image)
Definition at line 190 of file HistoryPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryPojo.setImagepath (String imagepath)
Definition at line 206 of file HistoryPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryPojo.setRemarks (String remarks)
Definition at line 147 of file HistoryPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryPojo.setWard (String ward)
Definition at line 130 of file HistoryPojo.java.
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/pojo/HistoryPojo.java