Mo-BuzzPHI: org.cosmic.mobuzz.general.pojo.HistoryReportPojo Class Reference
org.cosmic.mobuzz.general.pojo.HistoryReportPojo Class Reference
Public Member Functions
HistoryReportPojo ()
HistoryReportPojo (int image, String id, String gps, String address, String date, String ward, String remarks, String assessment, String cmcmessage, String username, String fullname, String contnumber)
HistoryReportPojo (String id, String gps, String address, String date, String ward, String remarks, String assessment, String cmcmessage, String username, String fullname, String contnumber, String imagepath)
HistoryReportPojo (int image, String id, String gps, String address, String date, String ward, String remarks, String assessment, String cmcmessage, String username, String fullname, String contnumber, String imagepath)
String getId ()
void setId (String id)
String getGps ()
void setGps (String gps)
String getAddress ()
void setAddress (String address)
String getDate ()
void setDate (String date)
String getWard ()
void setWard (String ward)
String getRemarks ()
void setRemarks (String remarks)
String getAssessment ()
void setAssessment (String assessment)
String getCmcmessage ()
void setCmcmessage (String cmcmessage)
String getUsername ()
void setUsername (String username)
int getImage ()
void setImage (int image)
String getFullname ()
void setFullname (String fullname)
String getContnumber ()
void setContnumber (String contnumber)
String getImagepath ()
void setImagepath (String imagepath)
Detailed Description
Definition at line 5 of file HistoryReportPojo.java.
Constructor & Destructor Documentation
org.cosmic.mobuzz.general.pojo.HistoryReportPojo.HistoryReportPojo ()
Definition at line 21 of file HistoryReportPojo.java.
org.cosmic.mobuzz.general.pojo.HistoryReportPojo.HistoryReportPojo (int image, String id, String gps, String address, String date, String ward, String remarks, String assessment, String cmcmessage, String username, String fullname, String contnumber)
Definition at line 25 of file HistoryReportPojo.java.
org.cosmic.mobuzz.general.pojo.HistoryReportPojo.HistoryReportPojo (String id, String gps, String address, String date, String ward, String remarks, String assessment, String cmcmessage, String username, String fullname, String contnumber, String imagepath)
Definition at line 41 of file HistoryReportPojo.java.
org.cosmic.mobuzz.general.pojo.HistoryReportPojo.HistoryReportPojo (int image, String id, String gps, String address, String date, String ward, String remarks, String assessment, String cmcmessage, String username, String fullname, String contnumber, String imagepath)
Definition at line 57 of file HistoryReportPojo.java.
Member Function Documentation
String org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getAddress ()
Definition at line 108 of file HistoryReportPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
String org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getAssessment ()
Definition at line 176 of file HistoryReportPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
String org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getCmcmessage ()
Definition at line 193 of file HistoryReportPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
String org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getContnumber ()
Definition at line 242 of file HistoryReportPojo.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
String org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getDate ()
Definition at line 125 of file HistoryReportPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
String org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getFullname ()
Definition at line 234 of file HistoryReportPojo.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
String org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getGps ()
Definition at line 91 of file HistoryReportPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
String org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getId ()
Definition at line 74 of file HistoryReportPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
int org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getImage ()
Definition at line 226 of file HistoryReportPojo.java.
String org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getImagepath ()
Definition at line 250 of file HistoryReportPojo.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
String org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getRemarks ()
Definition at line 159 of file HistoryReportPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
String org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getUsername ()
Definition at line 209 of file HistoryReportPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
String org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getWard ()
Definition at line 142 of file HistoryReportPojo.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setAddress (String address)
Definition at line 121 of file HistoryReportPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setAssessment (String assessment)
Definition at line 189 of file HistoryReportPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setCmcmessage (String cmcmessage)
Definition at line 205 of file HistoryReportPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setContnumber (String contnumber)
Definition at line 246 of file HistoryReportPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setDate (String date)
Definition at line 138 of file HistoryReportPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setFullname (String fullname)
Definition at line 238 of file HistoryReportPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setGps (String gps)
Definition at line 104 of file HistoryReportPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setId (String id)
Definition at line 87 of file HistoryReportPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setImage (int image)
Definition at line 230 of file HistoryReportPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setImagepath (String imagepath)
Definition at line 254 of file HistoryReportPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setRemarks (String remarks)
Definition at line 172 of file HistoryReportPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setUsername (String username)
Definition at line 221 of file HistoryReportPojo.java.
void org.cosmic.mobuzz.general.pojo.HistoryReportPojo.setWard (String ward)
Definition at line 155 of file HistoryReportPojo.java.
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/pojo/HistoryReportPojo.java