Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter Class Reference
org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter Class Reference
Inherits BaseAdapter, and OnClickListener.
Classes
class OnItemClickListener
Public Member Functions
BreedingsiteHistoryAdapter (Activity a)
BreedingsiteHistoryAdapter (Activity a, ArrayList d, Resources resLocal)
void clear ()
void add (HistoryPojo historyObj)
int getCount ()
HistoryPojo getItem (int position)
long getItemId (int position)
void onClick (View arg0)
View getView (int position, View convertView, ViewGroup parent)
Public Attributes
Resources res
Private Member Functions
CharSequence getString (int msgDataNoPara1)
Private Attributes
final Activity activity
final ArrayList< HistoryPojo > data = new ArrayList<HistoryPojo>()
final String[] wardsArray = new String[] {"Not in CMC jurisdiction", "Mattakkuliya (CMC ward)", "Modera (CMC ward)", "Mahawatte (CMC ward)", "Aluthmawatha (CMC ward)", "Lunupokuna (CMC ward)", "Bloemandhal (CMC ward)", "Kotahena East (CMC ward)", "Kotahena West (CMC ward)", "Kochchikade North (CMC ward)", "Gintupitiya (CMC ward)", "Masangas Weediya (CMC ward)", "New Bazaar (CMC ward)", "Grandpass North (CMC ward)", "Grandpass South (CMC ward)", "Maligawatte West (CMC ward)", "Aluthkade East (CMC ward)", "Aluthkade West (CMC ward)", "Kehelwatte (CMC ward)", "Kochchikade South (CMC ward)", "Fort (CMC ward)", "Kopannaweediya (CMC ward)", "Wekanda (CMC ward)", "Hunupitiya (CMC ward)", "Suduwella (CMC ward)", "Panchikawatte (CMC ward)", "Maradana (CMC ward)", "Maligakanda (CMC ward)", "Maligawatte East (CMC ward)", "Dematagoda (CMC ward)", "Wanathamulla (CMC ward)", "Kuppiyawatte East (CMC ward)", "Kuppiyawatte West (CMC ward)", "Borella North (CMC ward)", "Narahenpita (CMC ward)", "Borella South (CMC ward)", "Cinnamon Gardens (CMC ward)", "Kollupitiya (CMC ward)", "Bambalapitiya (CMC ward)", "Milagiriya (CMC ward)", "Thimbirigasyaya (CMC ward)", "Kirula (CMC ward)", "Havelok Twon (CMC ward)", "Wellewatte North (CMC ward)", "Kirillapone (CMC ward)", "Pamankada East (CMC ward)", "Pamankada West (CMC ward)", "Wellewatte South (CMC ward)"}
final String[] wardsArray_long = new String[] {"Not in CMC jurisdiction", "Mattakkuliya (CMC ward no: 01)", "Modera (CMC ward no: 02)", "Mahawatte (CMC ward no: 03)", "Aluthmawatha (CMC ward no: 04)", "Lunupokuna (CMC ward no: 05)", "Bloemandhal (CMC ward no: 06)", "Kotahena East (CMC ward no: 07)", "Kotahena West (CMC ward no: 08)", "Kochchikade North (CMC ward no: 09)", "Gintupitiya (CMC ward no: 10)", "Masangas Weediya (CMC ward no: 11)", "New Bazaar (CMC ward no: 12)", "Grandpass North (CMC ward no: 13)", "Grandpass South (CMC ward no: 14)", "Maligawatte West (CMC ward no: 15)", "Aluthkade East (CMC ward no: 16)", "Aluthkade West (CMC ward no: 17)", "Kehelwatte (CMC ward no: 18)", "Kochchikade South (CMC ward no: 19)", "Fort (CMC ward no: 20)", "Kopannaweediya (CMC ward no: 21)", "Wekanda (CMC ward no: 22)", "Hunupitiya (CMC ward no: 23)", "Suduwella (CMC ward no: 24)", "Panchikawatte (CMC ward no: 25)", "Maradana (CMC ward no: 26)", "Maligakanda (CMC ward no: 27)", "Maligawatte East (CMC ward no: 28)", "Dematagoda (CMC ward no: 29)", "Wanathamulla (CMC ward no: 30)", "Kuppiyawatte East (CMC ward no: 31)", "Kuppiyawatte West (CMC ward no: 32)", "Borella North (CMC ward no: 33)", "Narahenpita (CMC ward no: 34)", "Borella South (CMC ward no: 35)", "Cinnamon Gardens (CMC ward no: 36)", "Kollupitiya (CMC ward no: 37)", "Bambalapitiya (CMC ward no: 38)", "Milagiriya (CMC ward no: 39)", "Thimbirigasyaya (CMC ward no: 40)", "Kirula (CMC ward no: 41)", "Havelok Twon (CMC ward no: 42)", "Wellewatte North (CMC ward no: 43)", "Kirillapone (CMC ward no: 44)", "Pamankada East (CMC ward no: 45)", "Pamankada West (CMC ward no: 46)", "Wellewatte South (CMC ward no: 47)"}
final String TAG = BreedingsiteHistoryAdapter.class.getName()
Static Private Attributes
static LayoutInflater inflater = null
Detailed Description
Definition at line 23 of file BreedingsiteHistoryAdapter.java.
Constructor & Destructor Documentation
org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.BreedingsiteHistoryAdapter (Activity a)
Definition at line 36 of file BreedingsiteHistoryAdapter.java.
References org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.activity, and org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.inflater.
org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.BreedingsiteHistoryAdapter (Activity a, ArrayList d, Resources resLocal)
Definition at line 42 of file BreedingsiteHistoryAdapter.java.
References org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.activity, org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.inflater, and org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.res.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.add (HistoryPojo historyObj)
Definition at line 55 of file BreedingsiteHistoryAdapter.java.
void org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.clear ()
Definition at line 49 of file BreedingsiteHistoryAdapter.java.
References org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.data.
int org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.getCount ()
Definition at line 60 of file BreedingsiteHistoryAdapter.java.
HistoryPojo org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.getItem (int position)
Definition at line 65 of file BreedingsiteHistoryAdapter.java.
Referenced by org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.OnItemClickListener.onClick().
long org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.getItemId (int position)
Definition at line 70 of file BreedingsiteHistoryAdapter.java.
CharSequence org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.getString (int msgDataNoPara1) private
Definition at line 142 of file BreedingsiteHistoryAdapter.java.
Referenced by org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.getView().
View org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.getView (int position, View convertView, ViewGroup parent)
Definition at line 79 of file BreedingsiteHistoryAdapter.java.
References org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.activity, org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.data, org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.getString(), org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.TAG, and org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.wardsArray.
void org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.onClick (View arg0)
Definition at line 75 of file BreedingsiteHistoryAdapter.java.
Member Data Documentation
final Activity org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.activity private
Definition at line 25 of file BreedingsiteHistoryAdapter.java.
Referenced by org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.BreedingsiteHistoryAdapter(), org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.getView(), and org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.OnItemClickListener.onClick().
final ArrayList<HistoryPojo> org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.data = new ArrayList<HistoryPojo>() private
Definition at line 30 of file BreedingsiteHistoryAdapter.java.
Referenced by org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.clear(), and org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.getView().
LayoutInflater org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.inflater = null static private
Definition at line 26 of file BreedingsiteHistoryAdapter.java.
Referenced by org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.BreedingsiteHistoryAdapter().
Resources org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.res
Definition at line 27 of file BreedingsiteHistoryAdapter.java.
Referenced by org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.BreedingsiteHistoryAdapter().
final String org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.TAG = BreedingsiteHistoryAdapter.class.getName() private
Definition at line 34 of file BreedingsiteHistoryAdapter.java.
Referenced by org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.getView(), and org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.OnItemClickListener.onClick().
final String [] org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.wardsArray = new String[] {"Not in CMC jurisdiction", "Mattakkuliya (CMC ward)", "Modera (CMC ward)", "Mahawatte (CMC ward)", "Aluthmawatha (CMC ward)", "Lunupokuna (CMC ward)", "Bloemandhal (CMC ward)", "Kotahena East (CMC ward)", "Kotahena West (CMC ward)", "Kochchikade North (CMC ward)", "Gintupitiya (CMC ward)", "Masangas Weediya (CMC ward)", "New Bazaar (CMC ward)", "Grandpass North (CMC ward)", "Grandpass South (CMC ward)", "Maligawatte West (CMC ward)", "Aluthkade East (CMC ward)", "Aluthkade West (CMC ward)", "Kehelwatte (CMC ward)", "Kochchikade South (CMC ward)", "Fort (CMC ward)", "Kopannaweediya (CMC ward)", "Wekanda (CMC ward)", "Hunupitiya (CMC ward)", "Suduwella (CMC ward)", "Panchikawatte (CMC ward)", "Maradana (CMC ward)", "Maligakanda (CMC ward)", "Maligawatte East (CMC ward)", "Dematagoda (CMC ward)", "Wanathamulla (CMC ward)", "Kuppiyawatte East (CMC ward)", "Kuppiyawatte West (CMC ward)", "Borella North (CMC ward)", "Narahenpita (CMC ward)", "Borella South (CMC ward)", "Cinnamon Gardens (CMC ward)", "Kollupitiya (CMC ward)", "Bambalapitiya (CMC ward)", "Milagiriya (CMC ward)", "Thimbirigasyaya (CMC ward)", "Kirula (CMC ward)", "Havelok Twon (CMC ward)", "Wellewatte North (CMC ward)", "Kirillapone (CMC ward)", "Pamankada East (CMC ward)", "Pamankada West (CMC ward)", "Wellewatte South (CMC ward)"} private
Definition at line 31 of file BreedingsiteHistoryAdapter.java.
Referenced by org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.getView(), and org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.OnItemClickListener.onClick().
final String [] org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.wardsArray_long = new String[] {"Not in CMC jurisdiction", "Mattakkuliya (CMC ward no: 01)", "Modera (CMC ward no: 02)", "Mahawatte (CMC ward no: 03)", "Aluthmawatha (CMC ward no: 04)", "Lunupokuna (CMC ward no: 05)", "Bloemandhal (CMC ward no: 06)", "Kotahena East (CMC ward no: 07)", "Kotahena West (CMC ward no: 08)", "Kochchikade North (CMC ward no: 09)", "Gintupitiya (CMC ward no: 10)", "Masangas Weediya (CMC ward no: 11)", "New Bazaar (CMC ward no: 12)", "Grandpass North (CMC ward no: 13)", "Grandpass South (CMC ward no: 14)", "Maligawatte West (CMC ward no: 15)", "Aluthkade East (CMC ward no: 16)", "Aluthkade West (CMC ward no: 17)", "Kehelwatte (CMC ward no: 18)", "Kochchikade South (CMC ward no: 19)", "Fort (CMC ward no: 20)", "Kopannaweediya (CMC ward no: 21)", "Wekanda (CMC ward no: 22)", "Hunupitiya (CMC ward no: 23)", "Suduwella (CMC ward no: 24)", "Panchikawatte (CMC ward no: 25)", "Maradana (CMC ward no: 26)", "Maligakanda (CMC ward no: 27)", "Maligawatte East (CMC ward no: 28)", "Dematagoda (CMC ward no: 29)", "Wanathamulla (CMC ward no: 30)", "Kuppiyawatte East (CMC ward no: 31)", "Kuppiyawatte West (CMC ward no: 32)", "Borella North (CMC ward no: 33)", "Narahenpita (CMC ward no: 34)", "Borella South (CMC ward no: 35)", "Cinnamon Gardens (CMC ward no: 36)", "Kollupitiya (CMC ward no: 37)", "Bambalapitiya (CMC ward no: 38)", "Milagiriya (CMC ward no: 39)", "Thimbirigasyaya (CMC ward no: 40)", "Kirula (CMC ward no: 41)", "Havelok Twon (CMC ward no: 42)", "Wellewatte North (CMC ward no: 43)", "Kirillapone (CMC ward no: 44)", "Pamankada East (CMC ward no: 45)", "Pamankada West (CMC ward no: 46)", "Wellewatte South (CMC ward no: 47)"} private
Definition at line 33 of file BreedingsiteHistoryAdapter.java.
Referenced by org.cosmic.mobuzz.general.ui.support.BreedingsiteHistoryAdapter.OnItemClickListener.onClick().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/support/BreedingsiteHistoryAdapter.java