Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics Class Reference
org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics Class Reference
Inherits Fragment.
Public Member Functions
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onResume ()
void onPause ()
void setUserVisibleHint (boolean isFragmentVisible)
Private Attributes
TextView txt_dengue_statistics_title1
final String TAG = UiEducationSubpageStatistics.class.getName()
Detailed Description
Definition at line 17 of file UiEducationSubpageStatistics.java.
Member Function Documentation
View org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 27 of file UiEducationSubpageStatistics.java.
References org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.txt_dengue_statistics_title1.
void org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.onPause ()
Definition at line 54 of file UiEducationSubpageStatistics.java.
References org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.TAG.
void org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.onResume ()
Definition at line 48 of file UiEducationSubpageStatistics.java.
References org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.TAG.
void org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.setUserVisibleHint (boolean isFragmentVisible)
Definition at line 60 of file UiEducationSubpageStatistics.java.
References org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.TAG.
Member Data Documentation
final String org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.TAG = UiEducationSubpageStatistics.class.getName() private
Definition at line 23 of file UiEducationSubpageStatistics.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.onPause(), org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.onResume(), and org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.setUserVisibleHint().
TextView org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.txt_dengue_statistics_title1 private
Definition at line 21 of file UiEducationSubpageStatistics.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducationSubpageStatistics.onCreateView().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiEducationSubpageStatistics.java