Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory Class Reference
org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory Class Reference
Inherits Fragment.
Classes
class downloadData
Public Member Functions
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onResume ()
void onPause ()
void setUserVisibleHint (boolean isFragmentVisible)
BreedingsiteHistoryAdapter getAdapter ()
void responseToResult (String result)
void decodeResult (String result)
Public Attributes
ArrayList< HistoryPojo > CustomListViewValuesArr = new ArrayList<HistoryPojo>()
Private Member Functions
void getHistory ()
boolean isNetworkAvailable ()
void popdNoInternet ()
void popdRequestFailed (String title, String content)
void popdReauth (String title, String content)
Private Attributes
Dialog progressDialog
String url_report_history
Typeface font
Detailed Description
Definition at line 45 of file UiBreedingsiteSubpageHistory.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.decodeResult (String result)
Definition at line 240 of file UiBreedingsiteSubpageHistory.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.popdRequestFailed(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.responseToResult().
BreedingsiteHistoryAdapter org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.getAdapter ()
Definition at line 102 of file UiBreedingsiteSubpageHistory.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.getHistory () private
Definition at line 106 of file UiBreedingsiteSubpageHistory.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.isNetworkAvailable(), org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.popdNoInternet(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.url_report_history.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.setUserVisibleHint().
boolean org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.isNetworkAvailable () private
Definition at line 277 of file UiBreedingsiteSubpageHistory.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.getHistory().
View org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 60 of file UiBreedingsiteSubpageHistory.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.font, and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.url_report_history.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.onPause ()
Definition at line 83 of file UiBreedingsiteSubpageHistory.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.onResume ()
Definition at line 77 of file UiBreedingsiteSubpageHistory.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.popdNoInternet () private
Definition at line 288 of file UiBreedingsiteSubpageHistory.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.getHistory().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.popdReauth (String title, String content) private
Definition at line 302 of file UiBreedingsiteSubpageHistory.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.responseToResult().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.popdRequestFailed (String title, String content) private
Definition at line 295 of file UiBreedingsiteSubpageHistory.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.decodeResult(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.responseToResult().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.responseToResult (String result)
Definition at line 174 of file UiBreedingsiteSubpageHistory.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.decodeResult(), org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getStatus(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.popdReauth(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.popdRequestFailed(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.downloadData.onPostExecute().
void org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.setUserVisibleHint (boolean isFragmentVisible)
Definition at line 93 of file UiBreedingsiteSubpageHistory.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.getHistory().
Member Data Documentation
ArrayList<HistoryPojo> org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.CustomListViewValuesArr = new ArrayList<HistoryPojo>()
Definition at line 48 of file UiBreedingsiteSubpageHistory.java.
Typeface org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.font private
Definition at line 51 of file UiBreedingsiteSubpageHistory.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.onCreateView().
Dialog org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.progressDialog private
Definition at line 47 of file UiBreedingsiteSubpageHistory.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.downloadData.onPostExecute(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.downloadData.onPreExecute().
String org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.url_report_history private
Definition at line 50 of file UiBreedingsiteSubpageHistory.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.getHistory(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.onCreateView().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiBreedingsiteSubpageHistory.java