Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiMapHotspots Class Reference
org.cosmic.mobuzz.general.ui.UiMapHotspots Class Reference
Inherits FragmentActivity, OnItemSelectedListener, OnMarkerClickListener, OnInfoWindowClickListener, and OnMarkerDragListener.
Classes
class FetchMapData
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
boolean onOptionsItemSelected (MenuItem item)
void onResume ()
void onPause ()
void onMarkerDrag (Marker arg0)
void onMarkerDragEnd (Marker arg0)
void onMarkerDragStart (Marker arg0)
void onInfoWindowClick (Marker arg0)
boolean onMarkerClick (Marker arg0)
void onItemSelected (AdapterView<?> arg0, View arg1, int arg2, long arg3)
void onNothingSelected (AdapterView<?> arg0)
void onBackPressed ()
void onDestroy ()
void responseToResult (String result)
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
void setUpMap ()
void getHotspots ()
void getWards ()
void getMohs ()
void getMohInfo ()
void popdRequestFailed (String title, String content)
void popdMarkerInfo (String title)
void popdReauth (String title, String content)
Private Attributes
GoogleMap mMap
LatLng latLng
Dialog progressDialog
final Context context = UiMapHotspots.this
TableRow tblr_colorcode
TextView txt_left
final String hotspotColor [] = { "#88B40404", "#7FFF0000", "#88F78181", "#88F6CECE", "#88F8E0E0", "#00FBEFF2" }
Typeface font
String url_map
String callofficenum = ""
Detailed Description
Definition at line 68 of file UiMapHotspots.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiMapHotspots.getHotspots () private
Definition at line 263 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, and org.cosmic.mobuzz.general.ui.UiMapHotspots.url_map.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.setUpMap().
void org.cosmic.mobuzz.general.ui.UiMapHotspots.getMohInfo () private
Definition at line 316 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.ui.UiMapHotspots.getMohs(), org.cosmic.mobuzz.general.ui.UiMapHotspots.onMarkerClick(), org.cosmic.mobuzz.general.ui.UiMapHotspots.popdMarkerInfo(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.setUpMap().
void org.cosmic.mobuzz.general.ui.UiMapHotspots.getMohs () private
Definition at line 303 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.ui.UiMapHotspots.hotspotColor.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.getMohInfo().
void org.cosmic.mobuzz.general.ui.UiMapHotspots.getWards () private
Definition at line 290 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.ui.UiMapHotspots.hotspotColor.
void org.cosmic.mobuzz.general.ui.UiMapHotspots.onBackPressed ()
Definition at line 224 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.ui.UiMapHotspots.context.
void org.cosmic.mobuzz.general.ui.UiMapHotspots.onCreate (Bundle savedInstanceState) protected
Definition at line 85 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.ui.UiMapHotspots.context, org.cosmic.mobuzz.general.ui.UiMapHotspots.font, org.cosmic.mobuzz.general.util.GlobalVariables.GPS_COLOMBO, org.cosmic.mobuzz.general.ui.UiMapHotspots.latLng, org.cosmic.mobuzz.general.ui.UiMapHotspots.setUpMap(), org.cosmic.mobuzz.general.util.LogAction.START, org.cosmic.mobuzz.general.ui.UiMapHotspots.tblr_colorcode, org.cosmic.mobuzz.general.ui.UiMapHotspots.txt_left, and org.cosmic.mobuzz.general.ui.UiMapHotspots.url_map.
boolean org.cosmic.mobuzz.general.ui.UiMapHotspots.onCreateOptionsMenu (Menu menu)
Definition at line 116 of file UiMapHotspots.java.
void org.cosmic.mobuzz.general.ui.UiMapHotspots.onDestroy ()
Definition at line 231 of file UiMapHotspots.java.
void org.cosmic.mobuzz.general.ui.UiMapHotspots.onInfoWindowClick (Marker arg0)
Definition at line 200 of file UiMapHotspots.java.
void org.cosmic.mobuzz.general.ui.UiMapHotspots.onItemSelected (AdapterView<?> arg0, View arg1, int arg2, long arg3)
Definition at line 212 of file UiMapHotspots.java.
boolean org.cosmic.mobuzz.general.ui.UiMapHotspots.onMarkerClick (Marker arg0)
Definition at line 206 of file UiMapHotspots.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.getMohInfo().
void org.cosmic.mobuzz.general.ui.UiMapHotspots.onMarkerDrag (Marker arg0)
Definition at line 182 of file UiMapHotspots.java.
void org.cosmic.mobuzz.general.ui.UiMapHotspots.onMarkerDragEnd (Marker arg0)
Definition at line 188 of file UiMapHotspots.java.
void org.cosmic.mobuzz.general.ui.UiMapHotspots.onMarkerDragStart (Marker arg0)
Definition at line 194 of file UiMapHotspots.java.
void org.cosmic.mobuzz.general.ui.UiMapHotspots.onNothingSelected (AdapterView<?> arg0)
Definition at line 218 of file UiMapHotspots.java.
boolean org.cosmic.mobuzz.general.ui.UiMapHotspots.onOptionsItemSelected (MenuItem item)
Definition at line 123 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.ui.UiMapHotspots.mMap.
void org.cosmic.mobuzz.general.ui.UiMapHotspots.onPause ()
Definition at line 162 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.ui.UiMapHotspots.context, org.cosmic.mobuzz.general.ui.UiMapHotspots.mMap, and org.cosmic.mobuzz.general.ui.UiMapHotspots.progressDialog.
void org.cosmic.mobuzz.general.ui.UiMapHotspots.onResume ()
Definition at line 156 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.ui.UiMapHotspots.context.
void org.cosmic.mobuzz.general.ui.UiMapHotspots.popdMarkerInfo (String title) private
Definition at line 563 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.ui.UiMapHotspots.callofficenum, and org.cosmic.mobuzz.general.ui.UiMapHotspots.context.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.getMohInfo().
void org.cosmic.mobuzz.general.ui.UiMapHotspots.popdReauth (String title, String content) private
Definition at line 640 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.ui.UiMapHotspots.context.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.responseToResult().
void org.cosmic.mobuzz.general.ui.UiMapHotspots.popdRequestFailed (String title, String content) private
Definition at line 555 of file UiMapHotspots.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.responseToResult().
void org.cosmic.mobuzz.general.ui.UiMapHotspots.responseToResult (String result)
Definition at line 377 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.ui.UiMapHotspots.context, org.cosmic.mobuzz.general.pojo.HotspotsClusterPojo.getFromdate(), org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getStatus(), org.cosmic.mobuzz.general.pojo.HotspotsClusterPojo.getTodate(), org.cosmic.mobuzz.general.ui.UiMapHotspots.popdReauth(), org.cosmic.mobuzz.general.ui.UiMapHotspots.popdRequestFailed(), org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.FetchMapData.onPostExecute().
void org.cosmic.mobuzz.general.ui.UiMapHotspots.setUpMap () private
Definition at line 238 of file UiMapHotspots.java.
References org.cosmic.mobuzz.general.ui.UiMapHotspots.context, org.cosmic.mobuzz.general.ui.UiMapHotspots.getHotspots(), org.cosmic.mobuzz.general.ui.UiMapHotspots.getMohInfo(), org.cosmic.mobuzz.general.ui.UiMapHotspots.latLng, and org.cosmic.mobuzz.general.ui.UiMapHotspots.mMap.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.onCreate().
Member Data Documentation
String org.cosmic.mobuzz.general.ui.UiMapHotspots.callofficenum = "" private
Definition at line 562 of file UiMapHotspots.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.popdMarkerInfo().
final Context org.cosmic.mobuzz.general.ui.UiMapHotspots.context = UiMapHotspots.this private
Definition at line 73 of file UiMapHotspots.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.onBackPressed(), org.cosmic.mobuzz.general.ui.UiMapHotspots.onCreate(), org.cosmic.mobuzz.general.ui.UiMapHotspots.onPause(), org.cosmic.mobuzz.general.ui.UiMapHotspots.FetchMapData.onPreExecute(), org.cosmic.mobuzz.general.ui.UiMapHotspots.onResume(), org.cosmic.mobuzz.general.ui.UiMapHotspots.popdMarkerInfo(), org.cosmic.mobuzz.general.ui.UiMapHotspots.popdReauth(), org.cosmic.mobuzz.general.ui.UiMapHotspots.responseToResult(), and org.cosmic.mobuzz.general.ui.UiMapHotspots.setUpMap().
Typeface org.cosmic.mobuzz.general.ui.UiMapHotspots.font private
Definition at line 78 of file UiMapHotspots.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.onCreate().
final String org.cosmic.mobuzz.general.ui.UiMapHotspots.hotspotColor[] = { "#88B40404", "#7FFF0000", "#88F78181", "#88F6CECE", "#88F8E0E0", "#00FBEFF2" } private
Definition at line 77 of file UiMapHotspots.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.getMohs(), and org.cosmic.mobuzz.general.ui.UiMapHotspots.getWards().
LatLng org.cosmic.mobuzz.general.ui.UiMapHotspots.latLng private
Definition at line 71 of file UiMapHotspots.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.onCreate(), and org.cosmic.mobuzz.general.ui.UiMapHotspots.setUpMap().
GoogleMap org.cosmic.mobuzz.general.ui.UiMapHotspots.mMap private
Definition at line 70 of file UiMapHotspots.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.onOptionsItemSelected(), org.cosmic.mobuzz.general.ui.UiMapHotspots.onPause(), and org.cosmic.mobuzz.general.ui.UiMapHotspots.setUpMap().
Dialog org.cosmic.mobuzz.general.ui.UiMapHotspots.progressDialog private
Definition at line 72 of file UiMapHotspots.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.onPause(), org.cosmic.mobuzz.general.ui.UiMapHotspots.FetchMapData.onPostExecute(), and org.cosmic.mobuzz.general.ui.UiMapHotspots.FetchMapData.onPreExecute().
TableRow org.cosmic.mobuzz.general.ui.UiMapHotspots.tblr_colorcode private
Definition at line 75 of file UiMapHotspots.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.onCreate().
TextView org.cosmic.mobuzz.general.ui.UiMapHotspots.txt_left private
Definition at line 76 of file UiMapHotspots.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.onCreate().
String org.cosmic.mobuzz.general.ui.UiMapHotspots.url_map private
Definition at line 79 of file UiMapHotspots.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapHotspots.getHotspots(), and org.cosmic.mobuzz.general.ui.UiMapHotspots.onCreate().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiMapHotspots.java