Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage Class Reference
org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage Class Reference
Inherits FragmentActivity, OnTabChangeListener, and OnPageChangeListener.
Classes
class TabFactory
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
void onResume ()
void onPause ()
void onPageScrollStateChanged (int arg0)
void onPageScrolled (int position, float positionOffset, int positionOffsetPixels)
void onPageSelected (int position)
void onTabChanged (String tabId)
void onBackPressed ()
void onDestroy ()
Protected Member Functions
void onCreate (Bundle savedInstanceState)
void onActivityResult (int requestCode, int resultCode, Intent intent)
Private Member Functions
void initialiseTabHost (Bundle args)
void intialiseViewPager ()
Static Private Member Functions
static void AddTab (FragmentManager supportFragmentManager, TabHost tabHost2, TabSpec setIndicator)
static void AddTab (UiBreedingsiteMainpage activity, TabHost tabHost, TabHost.TabSpec tabSpec)
Private Attributes
TabHost tabHost
ViewPager viewPager
BreedingsiteAdapter pagerAdapter
final String TAG = UiBreedingsiteMainpage.class.getName()
Detailed Description
Definition at line 32 of file UiBreedingsiteMainpage.java.
Member Function Documentation
static void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.AddTab (FragmentManager supportFragmentManager, TabHost tabHost2, TabSpec setIndicator) static private
Definition at line 156 of file UiBreedingsiteMainpage.java.
static void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.AddTab (UiBreedingsiteMainpage activity, TabHost tabHost, TabHost.TabSpec tabSpec) static private
Definition at line 162 of file UiBreedingsiteMainpage.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.initialiseTabHost (Bundle args) private
Definition at line 136 of file UiBreedingsiteMainpage.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.tabHost.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.intialiseViewPager () private
Definition at line 167 of file UiBreedingsiteMainpage.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onActivityResult (int requestCode, int resultCode, Intent intent) protected
Definition at line 60 of file UiBreedingsiteMainpage.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onBackPressed ()
Definition at line 120 of file UiBreedingsiteMainpage.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.TAG.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onCreate (Bundle savedInstanceState) protected
Definition at line 43 of file UiBreedingsiteMainpage.java.
References org.cosmic.mobuzz.general.util.LogAction.START, and org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.TAG.
boolean org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onCreateOptionsMenu (Menu menu)
Definition at line 71 of file UiBreedingsiteMainpage.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onDestroy ()
Definition at line 128 of file UiBreedingsiteMainpage.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onPageScrolled (int position, float positionOffset, int positionOffsetPixels)
Definition at line 92 of file UiBreedingsiteMainpage.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onPageScrollStateChanged (int arg0)
Definition at line 87 of file UiBreedingsiteMainpage.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onPageSelected (int position)
Definition at line 109 of file UiBreedingsiteMainpage.java.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onPause ()
Definition at line 82 of file UiBreedingsiteMainpage.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.TAG.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onResume ()
Definition at line 76 of file UiBreedingsiteMainpage.java.
References org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.TAG.
void org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onTabChanged (String tabId)
Definition at line 114 of file UiBreedingsiteMainpage.java.
Member Data Documentation
BreedingsiteAdapter org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.pagerAdapter private
Definition at line 37 of file UiBreedingsiteMainpage.java.
TabHost org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.tabHost private
Definition at line 35 of file UiBreedingsiteMainpage.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.initialiseTabHost().
final String org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.TAG = UiBreedingsiteMainpage.class.getName() private
Definition at line 40 of file UiBreedingsiteMainpage.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onBackPressed(), org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onCreate(), org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onPause(), and org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.onResume().
ViewPager org.cosmic.mobuzz.general.ui.UiBreedingsiteMainpage.viewPager private
Definition at line 36 of file UiBreedingsiteMainpage.java.
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiBreedingsiteMainpage.java