Mo-BuzzPHI: org.cosmic.mobuzz.general.MainActivity Class Reference
org.cosmic.mobuzz.general.MainActivity Class Reference
Inherits Activity.
Classes
class activateApp
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
void onBackPressed ()
void onPause ()
void responseToResult (String result)
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
void activationcode (String key)
void popdRequestFailed (String title, String content)
boolean isNetworkAvailable ()
void popdNoInternet ()
void progress (String message)
Private Attributes
Dialog progressDialog
SharedPreferences pref
final String TAG = MainActivity.class.getName()
String url_activation_code
Detailed Description
Definition at line 38 of file MainActivity.java.
Member Function Documentation
void org.cosmic.mobuzz.general.MainActivity.activationcode (String key) private
Definition at line 120 of file MainActivity.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.MainActivity.TAG, and org.cosmic.mobuzz.general.MainActivity.url_activation_code.
Referenced by org.cosmic.mobuzz.general.MainActivity.onCreate().
boolean org.cosmic.mobuzz.general.MainActivity.isNetworkAvailable () private
Definition at line 149 of file MainActivity.java.
Referenced by org.cosmic.mobuzz.general.MainActivity.onCreate().
void org.cosmic.mobuzz.general.MainActivity.onBackPressed ()
Definition at line 115 of file MainActivity.java.
void org.cosmic.mobuzz.general.MainActivity.onCreate (Bundle savedInstanceState) protected
Definition at line 55 of file MainActivity.java.
References org.cosmic.mobuzz.general.MainActivity.activationcode(), org.cosmic.mobuzz.general.MainActivity.isNetworkAvailable(), org.cosmic.mobuzz.general.MainActivity.popdNoInternet(), org.cosmic.mobuzz.general.MainActivity.pref, org.cosmic.mobuzz.general.MainActivity.url_activation_code, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
boolean org.cosmic.mobuzz.general.MainActivity.onCreateOptionsMenu (Menu menu)
Definition at line 110 of file MainActivity.java.
void org.cosmic.mobuzz.general.MainActivity.onPause ()
Definition at line 169 of file MainActivity.java.
void org.cosmic.mobuzz.general.MainActivity.popdNoInternet () private
Definition at line 160 of file MainActivity.java.
Referenced by org.cosmic.mobuzz.general.MainActivity.onCreate().
void org.cosmic.mobuzz.general.MainActivity.popdRequestFailed (String title, String content) private
Definition at line 142 of file MainActivity.java.
Referenced by org.cosmic.mobuzz.general.MainActivity.responseToResult().
void org.cosmic.mobuzz.general.MainActivity.progress (String message) private
Definition at line 287 of file MainActivity.java.
void org.cosmic.mobuzz.general.MainActivity.responseToResult (String result)
Definition at line 215 of file MainActivity.java.
References org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getStatus(), org.cosmic.mobuzz.general.MainActivity.popdRequestFailed(), org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.MainActivity.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.MainActivity.activateApp.onPostExecute().
Member Data Documentation
SharedPreferences org.cosmic.mobuzz.general.MainActivity.pref private
Definition at line 43 of file MainActivity.java.
Referenced by org.cosmic.mobuzz.general.MainActivity.onCreate().
Dialog org.cosmic.mobuzz.general.MainActivity.progressDialog private
Definition at line 42 of file MainActivity.java.
Referenced by org.cosmic.mobuzz.general.MainActivity.activateApp.onPostExecute(), and org.cosmic.mobuzz.general.MainActivity.activateApp.onPreExecute().
final String org.cosmic.mobuzz.general.MainActivity.TAG = MainActivity.class.getName() private
Definition at line 44 of file MainActivity.java.
Referenced by org.cosmic.mobuzz.general.MainActivity.activationcode(), and org.cosmic.mobuzz.general.MainActivity.responseToResult().
String org.cosmic.mobuzz.general.MainActivity.url_activation_code private
Definition at line 45 of file MainActivity.java.
Referenced by org.cosmic.mobuzz.general.MainActivity.activationcode(), and org.cosmic.mobuzz.general.MainActivity.onCreate().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/MainActivity.java