Mo-BuzzPHI: org.cosmic.mobuzz.general.util.GlobalIO Class Reference
org.cosmic.mobuzz.general.util.GlobalIO Class Reference
Static Public Member Functions
static void writeLog (Context context, String className, String logAction, boolean isAppend)
static boolean isConfig (Context context)
static String getConfig (Context context) throws IOException
static void setConfig (Context context, String strData, boolean isAppend) throws IOException
Detailed Description
Handle data read/write to the device storage
Definition at line 17 of file GlobalIO.java.
Member Function Documentation
static String org.cosmic.mobuzz.general.util.GlobalIO.getConfig (Context context) throws IOException static
Definition at line 39 of file GlobalIO.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.FILE_CONF_FILE.
Referenced by org.cosmic.mobuzz.general.ui.UiProfile.getLogData(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.getLogData().
static boolean org.cosmic.mobuzz.general.util.GlobalIO.isConfig (Context context) static
Definition at line 34 of file GlobalIO.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.FILE_CONF_FILE.
static void org.cosmic.mobuzz.general.util.GlobalIO.setConfig (Context context, String strData, boolean isAppend) throws IOException static
Definition at line 52 of file GlobalIO.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.FILE_CONF_FILE.
Referenced by org.cosmic.mobuzz.general.util.GlobalIO.writeLog().
static void org.cosmic.mobuzz.general.util.GlobalIO.writeLog (Context context, String className, String logAction, boolean isAppend) static
Definition at line 19 of file GlobalIO.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, and org.cosmic.mobuzz.general.util.GlobalIO.setConfig().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/util/GlobalIO.java