Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiMapReports Class Reference
org.cosmic.mobuzz.general.ui.UiMapReports Class Reference
Inherits FragmentActivity.
Classes
class downloadImage
class FetchMapData
class uploadChanges
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
boolean onOptionsItemSelected (MenuItem item)
void onResume ()
void onPause ()
void onBackPressed ()
void onDestroy ()
void responseToResult (String result, int action)
void responseToResult (String result)
void responseToUpload (String result, int i)
void popupDatePicker (final int picker)
Public Attributes
final String DATE_FORMAT = "yyyy-MM-dd"
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
void but_setDates ()
void setUpMap ()
void getHotspots (int action, String strfrom, String strto)
void getWards ()
boolean isValidDates ()
void manageCheckBoxes ()
void manageHotspots (HistoryReportPojo[] hps, int action)
void popdRequestFailed (String title, String content)
void popdRequestUpdate (String title, String content, final int i, boolean isUpdated)
void popdMarkerInfo (final int i, int action, final HistoryReportPojo[] hrps)
String getGalleryImage (String imageName)
void setGalleryImage (String imagePath)
void popdReauth (String title, String content)
void setImage (int id, String imagesize)
void setChanges (int id, String ward, String cmcmessage, int misusecounter, int blockuser, int i, String publicuser, int changeStatus)
void popdListAssessment ()
void popdListWards ()
Private Attributes
GoogleMap mMap
LatLng latLng
Dialog progressDialog
final Context context = UiMapReports.this
Typeface font
String url_map_report_new
String url_report_details
String url_map_reports_update
String[] cmcwards = new String[]{"Other", "01. Mattakkuliya", "02. Modera", "03. Mahawatte", "04. Aluthmawatha", "05. Lunupokuna", "06. Bloemandhal", "07. Kotahena East", "08. Kotahena West", "09. Kochchikade North", "10. Gintupitiya", "11. Masangas Weediya", "12. New Bazaar", "13. Grandpass North", "14. Grandpass South", "15. Maligawatte West", "16. Aluthkade East", "17. Aluthkade West", "18. Kehelwatte", "19. Kochchikade South", "20. Fort", "21. Kopannaweediya", "22. Wekanda", "23. Hunupitiya", "24. Suduwella", "25. Panchikawatte", "26. Maradana", "27. Maligakanda", "28. Maligawatte East", "29. Dematagoda", "30. Wanathamulla", "31. Kuppiyawatte East", "32. Kuppiyawatte West", "33. Borella North", "34. Narahenpita", "35. Borella South", "36. Cinnamon Gardens", "37. Kollupitiya", "38. Bambalapitiya", "39. Milagiriya", "40. Thimbirigasyaya", "41. Kirula", "42. Havelok Twon", "43. Wellewatte North", "44. Kirillapone", "45. Pamankada East", "46. Pamankada West", "47. Wellewatte South"}
String[] cmcmessages = new String[]{"The CMC thanks you for your cooperation!", "This message confirms that CMC has investigated your complaint, and is grateful for your observation!", "Your breeding site complaint has been assigned to the following division: Drainage.", "Your breeding site complaint has been assigned to the following division: Solid Waste.", "Your breeding site complaint has been assigned to the following division: District Engineer.", "Thank you for your complaint. The CMC has checked the site you complained and found that problem has been rectified.", "Thank you for your complaint. The CMC has checked the site you complained and no problem was found.", "The information you sent has been found to be irrelevant. Please note that repeated reporting of irrelevant information will result in your account being blocked by the CMC.", "Your account has been blocked."}
String[] cmcmessagesstyle = new String[]{"<font color=\"red\"><b>[Status: New]</b><br/>The CMC thanks you for your cooperation!</font>", "<font color=\"#088A08\"><br/><b>[Status: Accept]</b><br/>This message confirms that CMC has investigated your complaint, and is <b><u>grateful for your observation</u></b>!</font>", "<font color=\"#088A08\">Your breeding site complaint has been assigned to the following division: <b><u>Drainage</u></b>.</font>", "<font color=\"#088A08\">Your breeding site complaint has been assigned to the following division: <b><u>Solid Waste</u></b>.</font>", "<font color=\"#088A08\">Your breeding site complaint has been assigned to the following division: <b><u>District Engineer</u></b>.</font>", "<font color=\"#088A08\">Thank you for your complaint. The CMC has checked the site you complained and found that <b><u>problem has been rectified</u></b>.</font>", "<font color=\"#088A08\">Thank you for your complaint. The CMC has checked the site you complained and <b><u>no problem was found</u></b>.</font>", "<font color=\"#736F6E\"><br/><b>[Status: Reject]</b><br/><b><u>The information you sent has been found to be irrelevant</u></b>. Please note that repeated reporting of irrelevant information will result in your account being blocked by the CMC.</font>", "<font color=\"#736F6E\">Your account has been blocked.</font>"}
Detailed Description
Definition at line 86 of file UiMapReports.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiMapReports.but_setDates () private
Definition at line 179 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.popupDatePicker().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.onCreate().
String org.cosmic.mobuzz.general.ui.UiMapReports.getGalleryImage (String imageName) private
Definition at line 1153 of file UiMapReports.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
void org.cosmic.mobuzz.general.ui.UiMapReports.getHotspots (int action, String strfrom, String strto) private
Definition at line 295 of file UiMapReports.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, and org.cosmic.mobuzz.general.ui.UiMapReports.url_map_report_new.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.manageCheckBoxes().
void org.cosmic.mobuzz.general.ui.UiMapReports.getWards () private
Definition at line 336 of file UiMapReports.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.COLOR_WARD_OVERLAY.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.responseToResult().
boolean org.cosmic.mobuzz.general.ui.UiMapReports.isValidDates () private
Definition at line 352 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.manageCheckBoxes().
void org.cosmic.mobuzz.general.ui.UiMapReports.manageCheckBoxes () private
Definition at line 388 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.getHotspots(), and org.cosmic.mobuzz.general.ui.UiMapReports.isValidDates().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.onCreate().
void org.cosmic.mobuzz.general.ui.UiMapReports.manageHotspots (HistoryReportPojo[] hps, int action) private
Definition at line 644 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.context, org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.responseToResult().
void org.cosmic.mobuzz.general.ui.UiMapReports.onBackPressed ()
Definition at line 265 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.context.
void org.cosmic.mobuzz.general.ui.UiMapReports.onCreate (Bundle savedInstanceState) protected
Definition at line 125 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.but_setDates(), org.cosmic.mobuzz.general.ui.UiMapReports.context, org.cosmic.mobuzz.general.ui.UiMapReports.font, org.cosmic.mobuzz.general.util.GlobalVariables.GPS_COLOMBO, org.cosmic.mobuzz.general.ui.UiMapReports.latLng, org.cosmic.mobuzz.general.ui.UiMapReports.manageCheckBoxes(), org.cosmic.mobuzz.general.ui.UiMapReports.setUpMap(), org.cosmic.mobuzz.general.util.LogAction.START, org.cosmic.mobuzz.general.ui.UiMapReports.url_map_report_new, org.cosmic.mobuzz.general.ui.UiMapReports.url_map_reports_update, and org.cosmic.mobuzz.general.ui.UiMapReports.url_report_details.
boolean org.cosmic.mobuzz.general.ui.UiMapReports.onCreateOptionsMenu (Menu menu)
Definition at line 203 of file UiMapReports.java.
void org.cosmic.mobuzz.general.ui.UiMapReports.onDestroy ()
Definition at line 272 of file UiMapReports.java.
boolean org.cosmic.mobuzz.general.ui.UiMapReports.onOptionsItemSelected (MenuItem item)
Definition at line 210 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.mMap.
void org.cosmic.mobuzz.general.ui.UiMapReports.onPause ()
Definition at line 249 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.context, and org.cosmic.mobuzz.general.ui.UiMapReports.mMap.
void org.cosmic.mobuzz.general.ui.UiMapReports.onResume ()
Definition at line 243 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.context.
void org.cosmic.mobuzz.general.ui.UiMapReports.popdListAssessment () private
Definition at line 1571 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.cmcmessages, org.cosmic.mobuzz.general.ui.UiMapReports.cmcmessagesstyle, org.cosmic.mobuzz.general.ui.UiMapReports.context, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
void org.cosmic.mobuzz.general.ui.UiMapReports.popdListWards () private
Definition at line 1630 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.cmcwards, org.cosmic.mobuzz.general.ui.UiMapReports.context, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
void org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo (final int i, int action, final HistoryReportPojo[] hrps) private
Definition at line 813 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.cmcwards, org.cosmic.mobuzz.general.ui.UiMapReports.context, org.cosmic.mobuzz.general.ui.UiMapReports.font, org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getCmcmessage(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getContnumber(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getFullname(), org.cosmic.mobuzz.general.ui.UiMapReports.getGalleryImage(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getId(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getImagepath(), org.cosmic.mobuzz.general.pojo.ImagePojo.getImg_name(), org.cosmic.mobuzz.general.pojo.HistoryReportPojo.getUsername(), org.cosmic.mobuzz.general.util.GlobalVariables.IMAGE_THUMB_POSTFIX, org.cosmic.mobuzz.general.ui.UiMapReports.popdListAssessment(), org.cosmic.mobuzz.general.ui.UiMapReports.popdListWards(), org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, org.cosmic.mobuzz.general.ui.UiMapReports.setChanges(), org.cosmic.mobuzz.general.ui.UiMapReports.setGalleryImage(), org.cosmic.mobuzz.general.ui.UiMapReports.setImage(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.manageHotspots().
void org.cosmic.mobuzz.general.ui.UiMapReports.popdReauth (String title, String content) private
Definition at line 1229 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.context.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.responseToResult(), and org.cosmic.mobuzz.general.ui.UiMapReports.responseToUpload().
void org.cosmic.mobuzz.general.ui.UiMapReports.popdRequestFailed (String title, String content) private
Definition at line 780 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.responseToResult(), and org.cosmic.mobuzz.general.ui.UiMapReports.responseToUpload().
void org.cosmic.mobuzz.general.ui.UiMapReports.popdRequestUpdate (String title, String content, final int i, boolean isUpdated) private
Definition at line 788 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.responseToUpload().
void org.cosmic.mobuzz.general.ui.UiMapReports.popupDatePicker (final int picker)
Definition at line 1694 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.context, org.cosmic.mobuzz.general.ui.UiMapReports.DATE_FORMAT, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.but_setDates().
void org.cosmic.mobuzz.general.ui.UiMapReports.responseToResult (String result, int action)
Definition at line 549 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.context, org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getStatus(), org.cosmic.mobuzz.general.ui.UiMapReports.getWards(), org.cosmic.mobuzz.general.ui.UiMapReports.manageHotspots(), org.cosmic.mobuzz.general.ui.UiMapReports.popdReauth(), org.cosmic.mobuzz.general.ui.UiMapReports.popdRequestFailed(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.FetchMapData.onPostExecute(), and org.cosmic.mobuzz.general.ui.UiMapReports.downloadImage.onPostExecute().
void org.cosmic.mobuzz.general.ui.UiMapReports.responseToResult (String result)
Definition at line 1320 of file UiMapReports.java.
References org.cosmic.mobuzz.general.pojo.ImagePojo.getImg_type(), org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getStatus(), org.cosmic.mobuzz.general.ui.UiMapReports.popdReauth(), org.cosmic.mobuzz.general.ui.UiMapReports.popdRequestFailed(), org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
void org.cosmic.mobuzz.general.ui.UiMapReports.responseToUpload (String result, int i)
Definition at line 1495 of file UiMapReports.java.
References org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getStatus(), org.cosmic.mobuzz.general.ui.UiMapReports.popdReauth(), org.cosmic.mobuzz.general.ui.UiMapReports.popdRequestFailed(), org.cosmic.mobuzz.general.ui.UiMapReports.popdRequestUpdate(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.uploadChanges.onPostExecute().
void org.cosmic.mobuzz.general.ui.UiMapReports.setChanges (int id, String ward, String cmcmessage, int misusecounter, int blockuser, int i, String publicuser, int changeStatus) private
Definition at line 1417 of file UiMapReports.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, and org.cosmic.mobuzz.general.ui.UiMapReports.url_map_reports_update.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
void org.cosmic.mobuzz.general.ui.UiMapReports.setGalleryImage (String imagePath) private
Definition at line 1221 of file UiMapReports.java.
References org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
void org.cosmic.mobuzz.general.ui.UiMapReports.setImage (int id, String imagesize) private
Definition at line 1252 of file UiMapReports.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.MY_PREF, org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG, and org.cosmic.mobuzz.general.ui.UiMapReports.url_report_details.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
void org.cosmic.mobuzz.general.ui.UiMapReports.setUpMap () private
Definition at line 279 of file UiMapReports.java.
References org.cosmic.mobuzz.general.ui.UiMapReports.context, org.cosmic.mobuzz.general.ui.UiMapReports.latLng, and org.cosmic.mobuzz.general.ui.UiMapReports.mMap.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.onCreate().
Member Data Documentation
String [] org.cosmic.mobuzz.general.ui.UiMapReports.cmcmessages = new String[]{"The CMC thanks you for your cooperation!", "This message confirms that CMC has investigated your complaint, and is grateful for your observation!", "Your breeding site complaint has been assigned to the following division: Drainage.", "Your breeding site complaint has been assigned to the following division: Solid Waste.", "Your breeding site complaint has been assigned to the following division: District Engineer.", "Thank you for your complaint. The CMC has checked the site you complained and found that problem has been rectified.", "Thank you for your complaint. The CMC has checked the site you complained and no problem was found.", "The information you sent has been found to be irrelevant. Please note that repeated reporting of irrelevant information will result in your account being blocked by the CMC.", "Your account has been blocked."} private
Definition at line 118 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdListAssessment().
String [] org.cosmic.mobuzz.general.ui.UiMapReports.cmcmessagesstyle = new String[]{"<font color=\"red\"><b>[Status: New]</b><br/>The CMC thanks you for your cooperation!</font>", "<font color=\"#088A08\"><br/><b>[Status: Accept]</b><br/>This message confirms that CMC has investigated your complaint, and is <b><u>grateful for your observation</u></b>!</font>", "<font color=\"#088A08\">Your breeding site complaint has been assigned to the following division: <b><u>Drainage</u></b>.</font>", "<font color=\"#088A08\">Your breeding site complaint has been assigned to the following division: <b><u>Solid Waste</u></b>.</font>", "<font color=\"#088A08\">Your breeding site complaint has been assigned to the following division: <b><u>District Engineer</u></b>.</font>", "<font color=\"#088A08\">Thank you for your complaint. The CMC has checked the site you complained and found that <b><u>problem has been rectified</u></b>.</font>", "<font color=\"#088A08\">Thank you for your complaint. The CMC has checked the site you complained and <b><u>no problem was found</u></b>.</font>", "<font color=\"#736F6E\"><br/><b>[Status: Reject]</b><br/><b><u>The information you sent has been found to be irrelevant</u></b>. Please note that repeated reporting of irrelevant information will result in your account being blocked by the CMC.</font>", "<font color=\"#736F6E\">Your account has been blocked.</font>"} private
Definition at line 121 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdListAssessment().
String [] org.cosmic.mobuzz.general.ui.UiMapReports.cmcwards = new String[]{"Other", "01. Mattakkuliya", "02. Modera", "03. Mahawatte", "04. Aluthmawatha", "05. Lunupokuna", "06. Bloemandhal", "07. Kotahena East", "08. Kotahena West", "09. Kochchikade North", "10. Gintupitiya", "11. Masangas Weediya", "12. New Bazaar", "13. Grandpass North", "14. Grandpass South", "15. Maligawatte West", "16. Aluthkade East", "17. Aluthkade West", "18. Kehelwatte", "19. Kochchikade South", "20. Fort", "21. Kopannaweediya", "22. Wekanda", "23. Hunupitiya", "24. Suduwella", "25. Panchikawatte", "26. Maradana", "27. Maligakanda", "28. Maligawatte East", "29. Dematagoda", "30. Wanathamulla", "31. Kuppiyawatte East", "32. Kuppiyawatte West", "33. Borella North", "34. Narahenpita", "35. Borella South", "36. Cinnamon Gardens", "37. Kollupitiya", "38. Bambalapitiya", "39. Milagiriya", "40. Thimbirigasyaya", "41. Kirula", "42. Havelok Twon", "43. Wellewatte North", "44. Kirillapone", "45. Pamankada East", "46. Pamankada West", "47. Wellewatte South"} private
Definition at line 117 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popdListWards(), and org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
final Context org.cosmic.mobuzz.general.ui.UiMapReports.context = UiMapReports.this private
Definition at line 91 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.manageHotspots(), org.cosmic.mobuzz.general.ui.UiMapReports.onBackPressed(), org.cosmic.mobuzz.general.ui.UiMapReports.onCreate(), org.cosmic.mobuzz.general.ui.UiMapReports.onPause(), org.cosmic.mobuzz.general.ui.UiMapReports.FetchMapData.onPreExecute(), org.cosmic.mobuzz.general.ui.UiMapReports.downloadImage.onPreExecute(), org.cosmic.mobuzz.general.ui.UiMapReports.uploadChanges.onPreExecute(), org.cosmic.mobuzz.general.ui.UiMapReports.onResume(), org.cosmic.mobuzz.general.ui.UiMapReports.popdListAssessment(), org.cosmic.mobuzz.general.ui.UiMapReports.popdListWards(), org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo(), org.cosmic.mobuzz.general.ui.UiMapReports.popdReauth(), org.cosmic.mobuzz.general.ui.UiMapReports.popupDatePicker(), org.cosmic.mobuzz.general.ui.UiMapReports.responseToResult(), and org.cosmic.mobuzz.general.ui.UiMapReports.setUpMap().
final String org.cosmic.mobuzz.general.ui.UiMapReports.DATE_FORMAT = "yyyy-MM-dd"
Definition at line 1693 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.popupDatePicker().
Typeface org.cosmic.mobuzz.general.ui.UiMapReports.font private
Definition at line 94 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.onCreate(), and org.cosmic.mobuzz.general.ui.UiMapReports.popdMarkerInfo().
LatLng org.cosmic.mobuzz.general.ui.UiMapReports.latLng private
Definition at line 89 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.onCreate(), and org.cosmic.mobuzz.general.ui.UiMapReports.setUpMap().
GoogleMap org.cosmic.mobuzz.general.ui.UiMapReports.mMap private
Definition at line 88 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.onOptionsItemSelected(), org.cosmic.mobuzz.general.ui.UiMapReports.onPause(), and org.cosmic.mobuzz.general.ui.UiMapReports.setUpMap().
Dialog org.cosmic.mobuzz.general.ui.UiMapReports.progressDialog private
Definition at line 90 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.FetchMapData.onPostExecute(), org.cosmic.mobuzz.general.ui.UiMapReports.downloadImage.onPostExecute(), org.cosmic.mobuzz.general.ui.UiMapReports.uploadChanges.onPostExecute(), org.cosmic.mobuzz.general.ui.UiMapReports.FetchMapData.onPreExecute(), org.cosmic.mobuzz.general.ui.UiMapReports.downloadImage.onPreExecute(), and org.cosmic.mobuzz.general.ui.UiMapReports.uploadChanges.onPreExecute().
String org.cosmic.mobuzz.general.ui.UiMapReports.url_map_report_new private
Definition at line 95 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.getHotspots(), and org.cosmic.mobuzz.general.ui.UiMapReports.onCreate().
String org.cosmic.mobuzz.general.ui.UiMapReports.url_map_reports_update private
Definition at line 97 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.onCreate(), and org.cosmic.mobuzz.general.ui.UiMapReports.setChanges().
String org.cosmic.mobuzz.general.ui.UiMapReports.url_report_details private
Definition at line 96 of file UiMapReports.java.
Referenced by org.cosmic.mobuzz.general.ui.UiMapReports.onCreate(), and org.cosmic.mobuzz.general.ui.UiMapReports.setImage().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiMapReports.java