Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask Class Reference
org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask Class Reference
Inherits AsyncTask< String, Void, String >.
Public Member Functions
void responseToResult (String result)
Protected Member Functions
void onPreExecute ()
String doInBackground (String...params)
void onPostExecute (String result)
Detailed Description
Definition at line 537 of file UiProfileRegister.java.
Member Function Documentation
String org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.doInBackground (String... params) protected
Definition at line 557 of file UiProfileRegister.java.
void org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.onPostExecute (String result) protected
Definition at line 562 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.progressDialog, and org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.responseToResult().
void org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.onPreExecute () protected
Definition at line 540 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.ui.UiProfileRegister.context, and org.cosmic.mobuzz.general.ui.UiProfileRegister.progressDialog.
void org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.responseToResult (String result)
Definition at line 571 of file UiProfileRegister.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.CONN_EXCEPTION, org.cosmic.mobuzz.general.ui.UiProfileRegister.popdRegister(), org.cosmic.mobuzz.general.ui.UiProfileRegister.popdRequestFailed(), org.cosmic.mobuzz.general.ui.UiProfileRegister.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Referenced by org.cosmic.mobuzz.general.ui.UiProfileRegister.RegisterTask.onPostExecute().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiProfileRegister.java