Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiEducationMainpage Class Reference
org.cosmic.mobuzz.general.ui.UiEducationMainpage Class Reference
Inherits FragmentActivity, OnTabChangeListener, and OnPageChangeListener.
Classes
class TabFactory
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
void onResume ()
void onPause ()
void onBackPressed ()
void onDestroy ()
void onPageScrollStateChanged (int arg0)
void onPageScrolled (int position, float positionOffset, int positionOffsetPixels)
void onPageSelected (int position)
void onTabChanged (String tabId)
Protected Member Functions
void onCreate (Bundle savedInstanceState)
void onSaveInstanceState (Bundle outState)
Private Member Functions
void initialiseTabHost (Bundle args)
void intialiseViewPager ()
Static Private Member Functions
static void AddTab (UiEducationMainpage activity, TabHost tabHost, TabHost.TabSpec tabSpec)
Private Attributes
TabHost tabHost
ViewPager viewPager
EducationAdapter pagerAdapter
final String TAG = UiEducationMainpage.class.getName()
Detailed Description
Definition at line 25 of file UiEducationMainpage.java.
Member Function Documentation
static void org.cosmic.mobuzz.general.ui.UiEducationMainpage.AddTab (UiEducationMainpage activity, TabHost tabHost, TabHost.TabSpec tabSpec) static private
Definition at line 177 of file UiEducationMainpage.java.
void org.cosmic.mobuzz.general.ui.UiEducationMainpage.initialiseTabHost (Bundle args) private
Definition at line 154 of file UiEducationMainpage.java.
References org.cosmic.mobuzz.general.ui.UiEducationMainpage.tabHost.
void org.cosmic.mobuzz.general.ui.UiEducationMainpage.intialiseViewPager () private
Definition at line 182 of file UiEducationMainpage.java.
void org.cosmic.mobuzz.general.ui.UiEducationMainpage.onBackPressed ()
Definition at line 90 of file UiEducationMainpage.java.
References org.cosmic.mobuzz.general.ui.UiEducationMainpage.TAG.
void org.cosmic.mobuzz.general.ui.UiEducationMainpage.onCreate (Bundle savedInstanceState) protected
Definition at line 37 of file UiEducationMainpage.java.
References org.cosmic.mobuzz.general.util.LogAction.START, and org.cosmic.mobuzz.general.ui.UiEducationMainpage.TAG.
boolean org.cosmic.mobuzz.general.ui.UiEducationMainpage.onCreateOptionsMenu (Menu menu)
Definition at line 73 of file UiEducationMainpage.java.
void org.cosmic.mobuzz.general.ui.UiEducationMainpage.onDestroy ()
Definition at line 97 of file UiEducationMainpage.java.
void org.cosmic.mobuzz.general.ui.UiEducationMainpage.onPageScrolled (int position, float positionOffset, int positionOffsetPixels)
Definition at line 112 of file UiEducationMainpage.java.
void org.cosmic.mobuzz.general.ui.UiEducationMainpage.onPageScrollStateChanged (int arg0)
Definition at line 107 of file UiEducationMainpage.java.
void org.cosmic.mobuzz.general.ui.UiEducationMainpage.onPageSelected (int position)
Definition at line 129 of file UiEducationMainpage.java.
void org.cosmic.mobuzz.general.ui.UiEducationMainpage.onPause ()
Definition at line 84 of file UiEducationMainpage.java.
References org.cosmic.mobuzz.general.ui.UiEducationMainpage.TAG.
void org.cosmic.mobuzz.general.ui.UiEducationMainpage.onResume ()
Definition at line 78 of file UiEducationMainpage.java.
References org.cosmic.mobuzz.general.ui.UiEducationMainpage.TAG.
void org.cosmic.mobuzz.general.ui.UiEducationMainpage.onSaveInstanceState (Bundle outState) protected
Definition at line 103 of file UiEducationMainpage.java.
void org.cosmic.mobuzz.general.ui.UiEducationMainpage.onTabChanged (String tabId)
Definition at line 134 of file UiEducationMainpage.java.
Member Data Documentation
EducationAdapter org.cosmic.mobuzz.general.ui.UiEducationMainpage.pagerAdapter private
Definition at line 30 of file UiEducationMainpage.java.
TabHost org.cosmic.mobuzz.general.ui.UiEducationMainpage.tabHost private
Definition at line 28 of file UiEducationMainpage.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducationMainpage.initialiseTabHost().
final String org.cosmic.mobuzz.general.ui.UiEducationMainpage.TAG = UiEducationMainpage.class.getName() private
Definition at line 33 of file UiEducationMainpage.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducationMainpage.onBackPressed(), org.cosmic.mobuzz.general.ui.UiEducationMainpage.onCreate(), org.cosmic.mobuzz.general.ui.UiEducationMainpage.onPause(), and org.cosmic.mobuzz.general.ui.UiEducationMainpage.onResume().
ViewPager org.cosmic.mobuzz.general.ui.UiEducationMainpage.viewPager private
Definition at line 29 of file UiEducationMainpage.java.
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiEducationMainpage.java