Mo-BuzzPHI: org.cosmic.mobuzz.general.pojo.ProfileLoginPojo Class Reference
org.cosmic.mobuzz.general.pojo.ProfileLoginPojo Class Reference
Public Member Functions
ProfileLoginPojo (String status)
ProfileLoginPojo (String status, String language)
String getStatus ()
void setStatus (String status)
String getLanguage ()
void setLanguage (String language)
Detailed Description
Definition at line 3 of file ProfileLoginPojo.java.
Constructor & Destructor Documentation
org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.ProfileLoginPojo (String status)
Definition at line 8 of file ProfileLoginPojo.java.
org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.ProfileLoginPojo (String status, String language)
Definition at line 14 of file ProfileLoginPojo.java.
Member Function Documentation
String org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getLanguage ()
Definition at line 28 of file ProfileLoginPojo.java.
Referenced by org.cosmic.mobuzz.general.ui.UiProfileLogin.responseToResult().
String org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.getStatus ()
Definition at line 20 of file ProfileLoginPojo.java.
Referenced by org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageHistory.responseToResult(), org.cosmic.mobuzz.general.MainActivity.responseToResult(), org.cosmic.mobuzz.general.ui.UiProfileLogin.responseToResult(), org.cosmic.mobuzz.general.ui.UiMapHotspots.responseToResult(), org.cosmic.mobuzz.general.ui.UiBreedingsiteHistoryDetails.responseToResult(), org.cosmic.mobuzz.general.ui.UiMapReports.responseToResult(), org.cosmic.mobuzz.general.ui.UiBreedingsiteSubpageReport.responseToResult(), org.cosmic.mobuzz.general.ui.UiMapReports.responseToUpload(), org.cosmic.mobuzz.general.ui.UiProfile.updateViews(), and org.cosmic.mobuzz.general.ui.UiProfileEdit.updateViews().
void org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.setLanguage (String language)
Definition at line 32 of file ProfileLoginPojo.java.
void org.cosmic.mobuzz.general.pojo.ProfileLoginPojo.setStatus (String status)
Definition at line 24 of file ProfileLoginPojo.java.
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/pojo/ProfileLoginPojo.java