Mo-BuzzPHI: org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment Class Reference
org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment Class Reference
Inherits Fragment.
Classes
class webvHospical
Public Member Functions
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onResume ()
void onPause ()
void setUserVisibleHint (boolean isFragmentVisible)
boolean isNetworkAvailable ()
Private Member Functions
void InitVewView ()
Private Attributes
TextView txt_dengue_treatment_title1
WebView webv_dengue_treatment
String web_url = "https://maps.google.lk/maps?t=m&sll=6.9215305,79.8648533&sspn=0.2617848,0.351645&q=colombo+hospital&output=classic&dg=ntvb"
String web_data = "<html><body><div style='width: 100%; overflow: hidden; height: 100%; text-align: center;'>Connecting...<iframe width='100%' height='126%' frameborder='0' scrolling='no' style='border:0; margin-top: -150px;' src='https://maps.google.lk/maps?t=m&amp;q=colombo+hospital&amp;ie=UTF8&amp;hq=hospital&amp;hnear=Colombo,+Western+Province&amp;ll=6.916856,79.866862&amp;spn=0.048534,0.032677&amp;output=embed&amp;z=14'></iframe></div></body></html>"
final String TAG = UiEducationSubpageTreatment.class.getName()
Detailed Description
Definition at line 25 of file UiEducationSubpageTreatment.java.
Member Function Documentation
void org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.InitVewView () private
Definition at line 98 of file UiEducationSubpageTreatment.java.
References org.cosmic.mobuzz.general.network.Connectivity.NetworkConnectivity(), and org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.web_data.
Referenced by org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.onCreateView().
boolean org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.isNetworkAvailable ()
Definition at line 157 of file UiEducationSubpageTreatment.java.
View org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 43 of file UiEducationSubpageTreatment.java.
References org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.InitVewView(), org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.txt_dengue_treatment_title1, and org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.webv_dengue_treatment.
void org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.onPause ()
Definition at line 84 of file UiEducationSubpageTreatment.java.
References org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.TAG.
void org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.onResume ()
Definition at line 78 of file UiEducationSubpageTreatment.java.
References org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.TAG.
void org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.setUserVisibleHint (boolean isFragmentVisible)
Definition at line 90 of file UiEducationSubpageTreatment.java.
References org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.TAG.
Member Data Documentation
final String org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.TAG = UiEducationSubpageTreatment.class.getName() private
Definition at line 41 of file UiEducationSubpageTreatment.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.onPause(), org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.onResume(), and org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.setUserVisibleHint().
TextView org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.txt_dengue_treatment_title1 private
Definition at line 28 of file UiEducationSubpageTreatment.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.onCreateView().
String org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.web_data = "<html><body><div style='width: 100%; overflow: hidden; height: 100%; text-align: center;'>Connecting...<iframe width='100%' height='126%' frameborder='0' scrolling='no' style='border:0; margin-top: -150px;' src='https://maps.google.lk/maps?t=m&amp;q=colombo+hospital&amp;ie=UTF8&amp;hq=hospital&amp;hnear=Colombo,+Western+Province&amp;ll=6.916856,79.866862&amp;spn=0.048534,0.032677&amp;output=embed&amp;z=14'></iframe></div></body></html>" private
Definition at line 40 of file UiEducationSubpageTreatment.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.InitVewView().
String org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.web_url = "https://maps.google.lk/maps?t=m&sll=6.9215305,79.8648533&sspn=0.2617848,0.351645&q=colombo+hospital&output=classic&dg=ntvb" private
Definition at line 39 of file UiEducationSubpageTreatment.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.webvHospical.shouldOverrideUrlLoading().
WebView org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.webv_dengue_treatment private
Definition at line 38 of file UiEducationSubpageTreatment.java.
Referenced by org.cosmic.mobuzz.general.ui.UiEducationSubpageTreatment.onCreateView().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/ui/UiEducationSubpageTreatment.java