Mo-BuzzPHI: org.cosmic.mobuzz.general.network.HttpUpload Class Reference
org.cosmic.mobuzz.general.network.HttpUpload Class Reference
Inherits Activity.
Static Public Member Functions
static String uploadData (String jString, String targetURL)
static String uploadDataCache (String jString, String targetURL)
static ResponsePojo uploadRequestData (String jString, String targetURL)
Static Private Member Functions
static void statPrint (int code, String msg)
static void statPrint (String code, String msg)
Static Private Attributes
static final String TAG = HttpUpload.class.getName()
Detailed Description
Definition at line 26 of file HttpUpload.java.
Member Function Documentation
static void org.cosmic.mobuzz.general.network.HttpUpload.statPrint (int code, String msg) static private
Definition at line 293 of file HttpUpload.java.
Referenced by org.cosmic.mobuzz.general.network.HttpUpload.uploadData(), org.cosmic.mobuzz.general.network.HttpUpload.uploadDataCache(), and org.cosmic.mobuzz.general.network.HttpUpload.uploadRequestData().
static void org.cosmic.mobuzz.general.network.HttpUpload.statPrint (String code, String msg) static private
Definition at line 297 of file HttpUpload.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.PRINT_DEBUG.
static String org.cosmic.mobuzz.general.network.HttpUpload.uploadData (String jString, String targetURL) static
Definition at line 32 of file HttpUpload.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.CONN_EXCEPTION, org.cosmic.mobuzz.general.util.GlobalVariables.CONN_TIMEOUT, org.cosmic.mobuzz.general.util.GlobalVariables.OTHER_EXCEPTION, org.cosmic.mobuzz.general.network.HttpUpload.statPrint(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
static String org.cosmic.mobuzz.general.network.HttpUpload.uploadDataCache (String jString, String targetURL) static
Definition at line 115 of file HttpUpload.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.CONN_EXCEPTION, org.cosmic.mobuzz.general.util.GlobalVariables.CONN_TIMEOUT, org.cosmic.mobuzz.general.util.GlobalVariables.OTHER_EXCEPTION, org.cosmic.mobuzz.general.network.HttpUpload.statPrint(), and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
static ResponsePojo org.cosmic.mobuzz.general.network.HttpUpload.uploadRequestData (String jString, String targetURL) static
Definition at line 197 of file HttpUpload.java.
References org.cosmic.mobuzz.general.util.GlobalVariables.CONN_EXCEPTION, org.cosmic.mobuzz.general.util.GlobalVariables.CONN_TIMEOUT, org.cosmic.mobuzz.general.util.GlobalVariables.OTHER_EXCEPTION, org.cosmic.mobuzz.general.network.HttpUpload.statPrint(), org.cosmic.mobuzz.general.network.HttpUpload.TAG, and org.cosmic.mobuzz.general.util.GlobalMethods.validateString().
Member Data Documentation
final String org.cosmic.mobuzz.general.network.HttpUpload.TAG = HttpUpload.class.getName() static private
Definition at line 30 of file HttpUpload.java.
Referenced by org.cosmic.mobuzz.general.network.HttpUpload.uploadRequestData().
The documentation for this class was generated from the following file:
src/org/cosmic/mobuzz/general/network/HttpUpload.java